

%TC=1. [%TC=7.0%TC=1.]%TC=2. Zmodem....... %TC=7.94pc %TC=2.[Reccomended]
%TC=1. [%TC=7.1%TC=1.]%TC=3. Xmodem....... %TC=7.80pc
%TC=1. [%TC=7.2%TC=1.]%TC=3. Xmodem-1k.... %TC=7.85pc
%TC=1. [%TC=7.3%TC=1.]%TC=6. Ymodem....... %TC=7.84pc
%TC=1. [%TC=7.4%TC=1.]%TC=6. Ymodem-1k.... %TC=7.88pc
%TC=1. [%TC=7.5%TC=1.]%TC=6. Ymodem-g..... %TC=7.95pc %TC=2.[Best with ERROR correcting modem!]
%TC=1. [%TC=7.6%TC=1.]%TC=5. ZedZap....... %TC=7.97pc %TC=2.[Zmodem varient]

%TC=6.Please select %TC=7.0-6%TC=6. from above =>%TC=7. 