%CLS.%BOLD=0.%TC=6.‹‹‹‹‹   ‹‹‹‹‹  ‹‹‹‹‹ ‹‹‹‹‹  ‹‹‹‹‹
%TC=6.‹‹  ‹€ ‹‹  €€ ‹‹  €€ ‹‹‹‹€€ ‹‹‹‹‹   %TC=7.C) %TC=3.Call the Sysop    %TC=7.L) %TC=3.Leave FeedBack
%TC=6.€€‹‹€€ €€‹‹€€ €€‹‹€€ €€  €€ ‹‹‹€€   %TC=7.Q) %TC=2.Quit to Main Menu %TC=7.G) %TC=1.GoodBye [Logoff]
%TC=6.‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹
%TC=3.GAMES
%TC=7. U) %TC=6.Hack&Slash2 %TC=3.(The NEW version! All new users here please!!)
%TC=7. 0) %TC=6.Hack&Slash (Old game)    %TC=7.1) %TC=6.Space Empire Game 1    %TC=7.2) %TC=6.Space Empire Game 2
%TC=7. 3) %TC=6.Blackmar's Dungeon       %TC=7.4) %TC=6.G L O B A L  W A R !!  %TC=7.5) %TC=6.ParaWorld Adventure
%TC=7. 6) %TC=6.Knight-Realm             %TC=7.7) %TC=6.Lotto                  %TC=7.8) %TC=6.AnsiWarriors!
%TC=7. 9) %TC=6.What Animal?             %TC=7.P) %TC=6.Peg Solitaire          %TC=7.Z) %TC=6.Trivia!
%TC=7. H) %TC=6.Chess                    %TC=7.M) %TC=6.Master Mind
%TC=7. V) %TC=6.Knot!                    %TC=7.T) %TC=6.The Immortal Struggle!
%TC=3. Infocom Adventures!
%TC=7. B) %TC=6.Suspect                  %TC=7.D) %TC=6.L.G.O.Phobos           %TC=7.I) %TC=6.Infidel
%TC=7. J) %TC=6.Zork 1                   %TC=7.K) %TC=6.Zork 2                 %TC=7.O) %TC=6.Zork 3
%TC=7. W) %TC=6.Hollywood-Hi-Jinx        %TC=7.Y) %TC=6.Wishbringer            %TC=7.R) %TC=6.Planetfall
%TC=7. S) %TC=6.Hitchikers G.T.T.G       %TC=7.A) %TC=6.BallyHoo
%TC=3. UTILITIES
%TC=7. E) %TC=6.Enter the Database       %TC=7.F) %TC=6.Amiga Fish Disk Viewer
%TC=3. MISC
%TC=7. N) %TC=6.Never Ending Story
%TC=7. 
