%CLS.%TC=6.%BC=0.ÚÄÄÄÄÄÄ %TC=3.GAMES: %TC=6.ÄÄÄÄÄ¿ ÜÜÜÜÜ   ÜÜÜÜÜ  ÜÜÜÜÜ ÜÜÜÜÜ  ÜÜÜÜÜ ÚÄÄÄÄÄÄ %TC=3.INFOCOMS: %TC=6.ÄÄÄÄ¿
³%TC=7. 0  -  Hack&Slash  %TC=6.³ ÜÜ  ÜÛ ÜÜ  ÛÛ ÜÜ  ÛÛ ÜÜÜÜÛÛ ÜÜÜÜÜ ³%TC=7. A  -  Ballyhoo      %TC=6.³
³%TC=7. 1  -  Space Emp` 1%TC=6.³ ÛÛÜÜÛÛ ÛÛÜÜÛÛ ÛÛÜÜÛÛ ÛÛ  ÛÛ ÜÜÜÛÛ ³%TC=7. B  -  Suspect       %TC=6.³
³%TC=7. 2  -  Space Emp` 2%TC=6.³ ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ ³%TC=7. D  -  LGOP          %TC=6.³
³%TC=7. 3  -  Blackmar's  %TC=6.³  ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  ³%TC=7. I  -  Infidel       %TC=6.³
³%TC=7. 4  -  GLOBAL WAR! %TC=6.³     ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿    ³%TC=7. J  -  Zork1         %TC=6.³
³%TC=7. 5  -  ParaWorld   %TC=6.³     ³%TC=3. C  -  Call the Sysop   %TC=6.³    ³%TC=7. K  -  Zork2         %TC=6.³
³%TC=7. 6  -  Knight-Realm%TC=6.³     ³%TC=2. Q  -  Quit to Main Menu%TC=6.³    ³%TC=7. O  -  Zork3         %TC=6.³
³%TC=7. 7  -  Lotto       %TC=6.³     ³%TC=1. G  -  Goodbye Log-Off  %TC=6.³    ³%TC=7. R  -  Planetfall    %TC=6.³
³%TC=7. 8  -  AnsiWarriors%TC=6.³     ³%TC=7. E  -  Database         %TC=6.³    ³%TC=7. S  -  HHGTTG        %TC=6.³
³%TC=7. 9  -  What Animal?%TC=6.³     ³%TC=7. F  -  Fish Disk Viewer %TC=6.³    ³%TC=7. W  -  Hollywood HJ  %TC=6.³
³%TC=7. H  -  Chess       %TC=6.³     ³%TC=7. N  -  Neverending Story%TC=6.³    ³%TC=7. Y  -  Wishbringer   %TC=6.³
³%TC=7. M  -  Master Mind %TC=6.³     ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ    ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
³%TC=7. P  -  Solitaire   %TC=6.³
³%TC=7. T  -  TIS         %TC=6.³
³%TC=7. V  -  Knot!       %TC=6.³
³%TC=7. Z  -  Trivia      %TC=6.³
³%TC=7. X  -  DeepSpace!  %TC=6.³
ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ%TC=7.%BC=0.
