%CLS.%TC=7.%BC=0.


                               = PICTURE SIG =
%CURSOR_RIGHT=19.%TC=6.ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
%CURSOR_RIGHT=19.³  %TC=7.F   -   File Conferences%CURSOR_RIGHT=12.%TC=6.³
%CURSOR_RIGHT=19.³  %TC=7.M   -   Message Conferences%CURSOR_RIGHT=9.%TC=6.³
%CURSOR_RIGHT=19.³  %TC=7.C   -   Call For System Operator    %TC=6.³
%CURSOR_RIGHT=19.³  %TC=7.L   -   Leave Feedback to Operator  %TC=6.³
%CURSOR_RIGHT=19.³  %TC=7.P   -   Goto Edit Preferences Menu  %TC=6.³
%CURSOR_RIGHT=19.³  %TC=7.D   -   Entertainment Areas%CURSOR_RIGHT=9.%TC=6.³
%CURSOR_RIGHT=19.³  %TC=3.Q   -   Quit Back to Main Menu%CURSOR_RIGHT=6.%TC=6.³
%CURSOR_RIGHT=19.³  %TC=2.W   -   Waiting Mail?%CURSOR_RIGHT=15.%TC=6.³
%CURSOR_RIGHT=19.³  %TC=1.G   -   Terminate Connection%CURSOR_RIGHT=8.%TC=6.³
%CURSOR_RIGHT=19.³  %TC=7.N   -   New File Scan%CURSOR_RIGHT=15.%TC=6.³
%CURSOR_RIGHT=19.ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ%TC=7.
