
%CURSOR=0.%CLS.%BOLD=1.%TC=1.WARNING >>%BOLD=0.%TC=7.

%BOLD=1.%TC=7.You have %TC=1.exceeded%TC=7. both your 'file' and 'bytes' 
download ratios.%BOLD=0.%TC=7.

%TC=7.%BOLD=1.Files ratio:%BOLD=0.%TC=7.

For every '%ld' files downloaded you must upload at least one file.

%TC=7.%BOLD=1.Bytes ratio:%BOLD=0.%TC=7.

You have a download allowance which is based on the size of your
uploads (who said size doesnt matter!?) - For every 1byte uploaded
you will be awarded '%ld' download credits in return. Depending on
how supportive of the system you are your 'bonus ratio' can either
increase or decrease.

As a example of how this works:

If you upload a file of (lets say) 5120 bytes (5K) your account then be
credit with '%ld' worth of download bytes. This is calculated by
the upload size in bytes * your bonus ratio of '%ld'.

%TC=1.ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ%TC=3. Press a Key%TC=1. >>%TC=7.%WAITKEY.%CURSOR=1.