
%CURSOR=0.%CLS.%BOLD=1.%TC=1.WARNING >>%BOLD=0.%TC=7.

%BOLD=1.%TC=7.You have %TC=1.exceeded%TC=7. your file to download ratio.%BOLD=0.%TC=7.

For every '%ld' files downloaded you must upload at least one file.

Failing to keep within this limit or upload within the next few days
will result in the deletion of your account.

%TC=1.ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ%TC=3. Press a Key%TC=1. >>%TC=7.%WAITKEY.%CURSOR=1.