

%CURSOR=0.%BC=4.     FileName:%BC=0. %BOLD=1.%TC=1.%-12.12s%BOLD=0. 
%BC=4.%TC=7. Size of File:%BC=0. %BOLD=1.%TC=7.%4ldk%BOLD=0.
%BC=4.%TC=7.Date Uploaded:%BC=0. %BOLD=1.%TC=7.%-9.9s:%BOLD=0.

%BC=4.%TC=7.Enter a description that explains something about the file above.             
%BC=0.%BOLD=1.%TC=7.[-----------------------------------------------------------------------------]
%BC=0.%BOLD=0.%TC=7.%CURSOR=1.
