                                   %BOLD=1.%TC=1.WARNING >>%TC=7.

                    Not Enough Credits Left For Download%BOLD=0.

%TC=7.     The file '%s' is '%ld' bytes in size and you currently are
     allowed to mark '%ld' bytes worth of files for download. If you
     wish to download this file then will have to either remove some of
     the other files from your marked list or try and do the decent thing
     and upload to the system.

     %TC=1.ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ%TC=3. Press a Key%TC=1. >>%TC=7.%WAITKEY.