

%BC=4.%TC=7.Filename     :%BC=0. %TC=1.%BOLD=1.%-18s%BOLD=0. %BC=4.%TC=7.File Number   :%BC=0. %TC=7.%ld
%BC=4.%TC=7.Uploader     :%BC=0. %TC=7.%-18s %BC=4.%TC=7.File Size     :%BC=0. %TC=7.%ldk (%ld bytes)
%BC=4.%TC=7.Uploaded On  :%BC=0. %TC=7.%s %s %BC=4.%TC=7.Last Download :%BC=0. %TC=7.%s %s%BOLD=0.
%BC=4.%TC=7.Access Count :%BC=0. %TC=7.%-18ld %BC=4.%TC=7.Transfer Time :%BC=0. %BOLD=0.%TC=3.%02ld%BOLD=1. %TC=1.%BOLD=1.Hours, %BOLD=0.%TC=3.%02ld%BOLD=1. %TC=1.Mins, %BOLD=0.%TC=3.%02ld%BOLD=1. %TC=1.Secs %BOLD=0.
%BC=4.%TC=7.Short Desc   :%BC=0. %s

