/* C Headerfile generated by RevUp 1.2 */

#define VERSION		2
#define REVISION	5
#define DATE	"6.11.94"
#define VERS	"LogMaint 2.5"
#define VSTRING	"LogMaint 2.5 (6.11.94)\r\n"
#define VERSTAG	"\0$VER: LogMaint 2.5 (6.11.94)"
