;* ASM Includefile generated by RevUp 1.2 *

VERSION		EQU	2
REVISION	EQU	5
DATE	MACRO
		dc.b	'6.11.94'
	ENDM
VERS	MACRO
		dc.b	'LogMaint 2.5'
	ENDM
VSTRING	MACRO
		dc.b	'LogMaint 2.5 (6.11.94)',13,10,0
	ENDM
VERSTAG	MACRO
		dc.b	0,'$VER: LogMaint 2.5 (6.11.94)',0
	ENDM
