
; Script file to install reqtools.library 37

FailAt 20

Echo "*nreqtools.library Installation Script*n"
Version >NIL: LIBS:reqtools.library
If NOT ERROR
	Echo "Version of reqtools.library already installed:"
	Version LIBS:reqtools.library
	Echo ""
EndIf

Version >NIL: exec.library 37
If NOT WARN
	Echo "Your Amiga has AmigaDOS Release 2 (V37) or higher in ROM."
	Ask "Install special Kickstart 2.0 version of reqtools.library (37.726) ?"
	If WARN
		Copy kick20/reqtools.library LIBS:reqtools.library
		Echo "*nreqtools.library (2.0 version) copied to your Libs: directory."
		Avail >NIL: FLUSH
		Skip INSTALLED
	EndIf
EndIf

Ask "Install Kickstart 1.2/1.3 version of reqtools.library (37.600) ?"
If NOT WARN
	Skip Aborted
EndIf

Copy kick13/reqtools.library LIBS:reqtools.library
Echo "*nreqtools.library copied to your Libs: directory."

Lab INSTALLED

Echo "Installation complete.*n"
Skip END

Lab ABORTED

Echo "*nInstallation aborted!*n"

Lab END

Wait 5
EndCLI >NIL:
