failat 30

If EXISTS Doors:
  ECHO " "
 Else
  ECHO " "
  ECHO You MUST assign Doors: directory first!
  ECHO " "
  QUIT
EndIf

If NOT EXISTS Doors:mv/
  MAKEDIR Doors:MV
EndIf


If EXISTS Doors:mv/stat/
  ECHO "You already have Doors:mv/stat directory ?" 
  ECHO " "
  Ask  "Do you wish to DELETE [and lose ALL files & configs in it?] (y/N)" 
  If NOT WARN
      ECHO " "
      ECHO "Please, check your config or install door manualy?"
    QUIT
  Else
    ECHO "Are you absolutely sure that you want do DELETE  "
    Ask "all files in Doors:mv/stat directory ?        (y/N)"
    If WARN
      DELETE doors:mv/stat/#? ALL QUIET >nil:
    Else
      ECHO " "
      ECHO "Please, check your config or install door manualy?"
      QUIT
   EndIf
  EndIf
Else
  Makedir doors:Mv/Stat >nil:
EndIf

Echo " "
Echo "Copying Mad Virgin Door to Doors:MV/STAT/ directory"

COPY stat TO doors:mv/stat/ ALL CLONE QUIET
If NOT WARN
  ECHO ---------------------------------------------------------------------------
  ECHO "        Mad Virgin STATUS door V1.0b for DayDream BBS - AMIGA !"
  ECHO "                                                        (26.03.1997)"
  ECHO " "
  ECHO " INSTALATION OK !"
  ECHO " "
  ECHO " PLEASE READ THE DOCS before install this door on your BBS !!!!"
  ECHO ---------------------------------------------------------------------------
 Else
  ECHO "DAMN! Something is wrong!?"
 EndIf
wait 7
