*mmddyyyy Birthdays
*-------- ---------------------------------------------------------------
B0801  10 BC Claudius
B08011770 William Clark, explored Pacific Northwest with Lewis.
B08011779 Francis Scott Key, wrote the 'Star-Spangled Banner'.
B08011815 Richard Henry Dana, spent 2 years before the mast.
B08011819 Herman Melville
B08021924 Carrol O'Connor
B08021986 Me!  Do programs have life?
B08031811 Elisha Graves Otis, inventor of the safe elevator.
B08031940 Martin Sheen
B08041755 Nicolas-Jacque Conte, invented the modern pencil.
B08041792 Percy Bysshe Shelly
B08051850 Guy de Maupassant
B08051900 Queen Mother Elizabeth
B08051930 Neil Armstrong
B08061809 Lord Alfred Tennyson, poet laureate of England.
B08061881 Sir Alexander Fleming, cashed in on penicillin
B08071783 John Heathcoat, invented lace-making machinery
B08071876 Mata Hari
B08071886 Louis Alan Hazeltine, invented the neutrodyne circuit, making
B08071886Ccommercial radio possible.
B08081763 Charles Bullfinch, 1st US professional architect
B08081922 Rudi Gernreich, designed 1st women's topless swimsuit & the miniskirt
B08081930 Joan Mondale
B08081937 Dustin Hoffman
B08081938 Connie Stevens
B08091930 Betty Boop
B08101874 Herbert Hoover, 31st President (1929-1933)
B08101899 Jack Haley
B08111921 Alex Haley
B08121881 Cecil B. deMille, directed God.
B08121911 Mario Moreno, alias Cantinflas.
B08131655 Johann Christoph Denner, invented the clarinet.
B08131818 Lucy Stone, pioneer in Woman's Rights.
B08131860 Annie Oakley
B08131899 Alfred Hitchcock
B08131927 Fidel Castro
B08141946 Susan St. James
B08141959 Magic Johnson
B08151688 Frederich Wilhelm III
B08151769 Napoleon Bonaparte
B08151803 Sir James Douglas, father of British Columbia.
B08151912 Julia Child, chef.
B08151954 Princess Anne
B08161884 Hugo Gernsback, responsible for science fiction becoming an
B08161884Cindependent literary form.
B08161892 Harold Foster, cartoonist, created "Prince Valiant", known for
B08161892Cits fine drawing and historical detail.
B08161913 Menachim Begin
B08171786 Davy Crockett
B08171892 Mae West.  Go up and see her sometime.
B08171942 Robert De Niro
B08181597 Virginia Dare, 1st child born in America of English parents.
B08181834 Marshall Field (founded a Chicago-based store chain).
B08181937 Robert Redford
B08191646 John Flamsteed, 1st astronomer royal of England.
B08191785 Seth Thomas, pioneer in mass production of clocks.
B08191871 Orville Wright
B08191902 Ogden Nash
B08201833 Benjamin Harrison, 23rd President (1889-1893)
B08201890 H.P. Lovecraft
B08201942 Isaac Hayes
B08211660 Hubert Gautier, engineer, wrote 1st book on bridge building.
B08211906 Count Basie
B08211936 Wilt Chamberlain
B08221195 St. Anthony of Padua
B08221862 Claude Debussy, composer
B08221920 Ray Bradbury, science fiction author.
B08231443 Rudolphus Argricola
B08231754 Louis XVI
B08231869 James "Sunny Jim" Rolph, Mayor (1912-1931), Muni backer.
B08231912 Gene Kelly the screen dance legend
B08231934 I Dream of Barbara Eden.
B08241816 Sir Daniel Gooch, laid 1st successful trans-Atlantic cables
B08241886 William Francis Gibbs, naval architect, designed the Liberty ships
B08251819 Alan Pinkerton
B08251919 George Wallace
B08251927 Althea Gibson, 1st black tennis champion (in a major event)
B08251930 Sean Connery (the first 007).
B08261743 Lavoisier
B08261819 Prince Albert
B08261873 Lee De Forest, invented the Audion vacuum tube (radio tube).
B08261898 Peggy Guggenheim
B08261951 Delvene Delaney (Strop's Missus)
B08271882 Samuel Goldwyn, pioneer filmmaker
B08271899 C.S. Forester, historical novelist, created Horatio Hornblower
B08271908 Lyndon B. Johnson, 36th President (1963-1969)
B08271910 Mother Theresa
B08281749 Johann Wolfgang von Goethe, social philosopher
B08291809 Oliver Wendell Holmes
B08291923 Richard Attenborough
B08291938 Elliot Gould
B0830  12 BC Caligula
B08301797 Mary Shelley, wrote Frankenstein
B08301943 Jean Claude Killy
B08311821 Helmholz
B08311924 Buddy Hackett
B08311945 Itzhak Perlman
B08261930 Sean Connery

*mmddyyyy Events
*-------- ---------------------------------------------------------------
S08011291 the Everlasting League forms, the basis of the Swiss Confederation.
S08011734 Joseph Priestly discovers oxygen (wonder what he was
S08011734Cbreathing before).
S08011790 First U.S. Census
S08011794 Whisky Rebellion
S08011834 British Empire abolished slavery.
S08011852 Black Methodists in SF establish 1st black church, Zion Methodist.
S08011881 US Quarantine Station authorized for Angel Island.
S08011893 Shredded wheat patented.
S08011901 Burial within San Francisco City limits prohibited.
S08011907 Bank of Italy opens 1st branch at 3433 Mission Street.
S08011916 Hawaii National Park established.
S08011946 President Truman establishes Atomic Energy Commission.
S08011946 U.S. Atomic Energy Commission established.
S08011953 California introduces its Sales Tax (for Education).
S08011957 Completion of first solar heated commercial building.
S08011958 First Class postage up to 4 cents (had been 3 cents for 26 years).
S08011961 New San Francisco Hall of Justice opens.
S08021817 First steam boat embarks from St. Louis.
S08021873 1st trial run of an SF cable car, on Clay Street between
S08021873CKearny and Jones, downhill all the way, at 4AM.
S08021876 Wild Bill Hickock shot dead.
S08021877 San Francisco Public Library opens with 5000 volumes.
S08021889 San Francisco invaded by millions of crickets.
S08021923 President Harding dies at the Palace Hotel.
S08021943 J.F.K's PT boat sunk by Japanese destroyer.
S08031492 Columbus departs on his first voyage.
S08031880 American Canoe Association formed.
S08031921 First Aerial crop dusting.
S08041693 Champagne is invented by Dom Perignon.
S08041735 U.S. Freedom of press established.
S08041782 Mozart marries.
S08041790 United States Coast Guard founded.
S08041893 Lizzie Borden "took an axe".
S08041944 Nazis capture Anne Frank.
S08041964 Gulf of Tonkin incident.
S08051775 the 1st Spanish ship, 'San Carlos', enters San Francisco bay.
S08051858 Undersea cable completed across Atlantic Ocean.
S08051861 US levies its first Income Tax (3% of incomes over $800).
S08051864 The spectrum of a comet observed for 1st time, by Giovanni Donati.
S08051914 Traffic light installed in Cleveland
S08051963 Nuclear Test Ban Treaty signed.
S08051966 John Lennon claims Beatles more popular than Jesus.
S08061727 First U.S. convent opens.
S08061806 Formal end of the Holy Roman Empire.
S08061835 Bolivia gains its independence
S08061890 First person executed by electrocution in the U.S.
S08061926 the first woman swims the English Channel.
S08061945 the Atom Bomb was dropped on Hiroshima by the 'Enola Gay'.
S08071807 1st servicable steamboat, the Cleremont, goes on 1st voyage.
S08071820 Potatoes first planted in Hawaii.
S08071869 First photo of total solar eclipse taken.
S08071903 Calamity Jane dies.
S08071964 Gulf of Tonkin resolution.
S08091803 1st horses arrive in Hawaii.
S08091842 the US-Canada border defined by the Webster-Ashburton Treaty.
S08091848 Free Soil Party formed in U.S.
S08091942 Mohandis Gandhi arrested and imprisioned for 2 years.
S08091945 Nagasaki A-bomb detonated, 40,000 die.
S08091974 Nixon resigns and Gerald Ford sworn in as president.
S08101809 Ecuador gains its independence.
S08101833 Chicago population 300; incorporated as a village.
S08101842 Women and children banned from working underground in British mines.
S08101876 Alexander Graham Bell made 1st long-distance call from
S08101876CBrantford to Paris Ont. (13 km).
S08101933 Rin Tin Tin dies.
S08101973 1st BART train travels thru transbay tube to Montgomery St Station.
S08101981 Pete Rose tops Stan Musial's record of 3630 hits.
S08111888 The California Theatre closed (now a Pac Tel Phone Store).
S08111896 Electric light socket with pull chain patented.
S08121581 End of Battle for Tiaxcala - Aztecs fought
S08121581CCortez and lost 11,000 men.
S08121658 "Rattle Watch" first police force in America established.
S08121851 Issac Singer granted a patent for his sewing machine.
S08121982 Henry Fonda dies.
S08121985 JAL airlines flight 123 crashes killing 520 people.
S0813     International Left-handers Day
S08131876 Reciprocity Treaty between US and Hawaii ratified.
S08131923 "Yes, We have no bannanas" number 1 song in N. America.
S08131946 H.G. Wells dies.
S08131961 East Germany closes border between East and West Berlin.
S08131978 Saskatchewan Power Corp blacks out entire province (twice!)
S08141846 Henry David Thoreau jailed for tax resistance.
S08141900 Boxer Rebellion ends (Peking China).
S08141912 U.S. Marines sent to Nicaragua.
S08141923 Felix the cat debuts in comics.
S08141945 VJ Day - Japan surrendered to end World War II.
S08151901 Arch Rock, danger to Bay shipping, blasted with 30 tons of
S08151901Cnitrogelatin (and that ain't jello).
S08151911 Shortening introduced.
S08151934 3,000 foot bathysphere descent in Bahamas.
S08151935 Will Rogers dies in airplane crash.
S08151945 Riot in San Francisco celebrating end of World War II.
S08151945CSouth Korea liberated from Japanese rule.
S08151960 the Congo (Brazzaville) gains its independence.
S08161896 Gold discovered in Klondike.
S08161932 Betsy Von Furstenberg dies.
S08161948 Babe Ruth dies.
S08161969 Woodstock festival begins in New York.
S08161977 Elvis Presely dies.
S08171807 Robert Fulton's steam boat (Clermont) takes 1st trip up Hudson.
S08171858 1st bank in Hawaii opens.
S08171896 First motoring fatality.
S08171908 Bank of Italy opens its new headquarters at Clay & Montgomery.
S08171915 1st automobile electric starter motor patented.
S08171950 Indonesia gains its independence.
S08171961 Russians begin construction of Berlin wall.
S08181227 Genghis Kahn dies.
S08181914 Germany declares war on Russia.
S08181938 Wizard of Oz premiers.
S0819     Aviation Day
S0819     Admission Day (celebrated in Hawaii).
S08191692 5 people hanged for witchcraft (Salem Mass.).
S08191826 Canada Co. chartered to colonize Upper Canada (Ontario).
S08191890 Daughter's of the American revolution organized.
S08191960 Francis Gary Powers convicted of spying by USSR (U-2 incident)
S08191977 Groucho Marx dies.
S08191981 2 U.S. jets shoot down 2 Libyan jets.
S0820     Admission Day (celebrated in Hawaii).
S08201940 Exiled Leon Trotsky murdered (mexico).
S08201942 Dimout regulations implemented in San Francisco.
S08201956 Republicans start convention at the Cow Palace.
S08201977 Voyager II launched.
S08201979 Diana Nyad swims from Bahamas to Florida (89 miles).
S08211959 Hawaii became the 50th state.
S08211968 Soviet Union invades Czechoslovakia.
S08211971 George Jackson murdered.
S08221692 8 more people hanged for witchcraft (Salem).
S08221787 John Fitch's steamboat completes its tests, years before
S08221787CFulton builds his steamboat.
S08221911 Mona Lisa stolen from the Louvre.
S08231500 Columbus accused of mistreating natives - sent back
S08231500Cto Spain in chains.
S08231838 1st graduates get degree from women's college in U.S.
S08231869 1st carload of freight (boots & shoes) arrives in San Francisco,
S08231869Cfrom Boston, after a 16-day rail trip.
S08231872 1st Japanese commercial ship visits San Francisco with cargo of tea.
S08231889 1st ship-to-shore wireless message received in US:
S08231889CUS lightship to Cliff House.
S08231926 Rudolph Valentino dies.
S0824  79 Mt. Vesuvius erupts - Pompeii destroyed.
S08241814 British burn Washington D.C.
S08241869 Waffle Iron patented.
S08241909 Workers start pouring concrete for the Panama Canal.
S08241954 Communist Control Act signed into law by Pres. Eisenhower.
S08241989 Voyager II flies past Neptune.
S08251718 City of New Orleans founded.
S08251814 British destroy Liberty of Congress.
S08251825 Uruguay gains its independence.
S08251829 Steam engine Tom Thumb races horse drawn car and loses.
S08251864 Combination rail & ferry service available from SF to Alameda.
S08251877 Only recorded pistol duel between women.
S08251929 Graf Zeppelin passes over San Francisco, headed for Los Angeles
S08251929Cafter trans-Pacific voyage from Tokyo.
S08251981 Voyager II flies past Saturn.
S08261629 Cambridge Agreement pledged.  Massachusetts Bay Co. stockholders
S08261629Cagreed to emigrate to New England.
S08261791 John Fitch granted a US patent for his working steamboat.
S08261846 W. A. Bartlett appointed 1st US mayor of Yerba Buena (SF).
S08261883 Krakatoa; mightiest volcano ever, erupts.
S08261907 Houdini escapes from chains underwater at Aquatic Park in
S08261907C57 seconds.
S08261920 19th Amendment passes - Women's Suffrage granted (about time!)
S08261937 Pumping to build Treasure Island finished.
S08261939 1st TV broadcast of a major league ball game
S08261952 Fluoridation of San Francisco water begins.
S08271664 Dutch surrender New Amsterdam to British. Name changed
S08271664Cto New York City.
S08271859 1st successful oil well drilled near Titusville, Penn.
S08271883 Krakatoa, WEST of Java, blew apart (Top that, St Helens).
S08271904 1st car driver jailed for speeding.
S08271912 Tarzan first appears in print.
S08271928 Kellogg-Briand Pact, where 60 nations agreed to outlaw war
S08271928C(must have lost the document!).
S08271979 Lord Mountbatten assassinated by IRA.
S08281867 USA occupies Midway islands.
S08281906 1st electric car horn advertised
S08281920 19th Amendment takes effect - Women's suffrage.
S08281928 1st Commercial Radio airs.
S0829  30 John the Baptist beheaded.
S08291852 Brigham Young proclaims polygamy acceptable.
S08291914 'Arizonan' is the 1st vessel to arrive in SF via the Panama Canal.
S08291921 Ku Klux Klan tars 43 Texans.
S08291954 San Francisco International Airport (SFO) opens.
S0830  30 BC Cleopatra commits suicide.
S08301780 Benidict Arnold betrays the revolution.
S08301850 Honolulu, Hawaii becomes a city.
S08301963 USA - USSR hotline goes into operation.
S08301979 1st recorded occurrance of a comet hitting the sun (the energy
S08301979Creleased was about equal to 1 million hydrogen bombs).
S08301982 Ingrid Bergman dies.
S08311290 King Edwared exiles all Jews from England.
S08311850 The California Pioneers organized at Montgomery & Clay Streets.
S08311881 1st US tennis championships played.
S08311886 Crocker-Woolworth National Bank organized.
S08311955 GM demonstrates 1st solar powered car.
S08311969 Rocky Marciano dies in a plane crash.
S08311980 Solidarity Labor Union in Poland is founded.
