/* C Headerfile generated by RevUp 1.2 */

#define VERSION		1
#define REVISION	2
#define DATE	"15.10.94"
#define VERS	"Editor 1.2"
#define VSTRING	"Editor 1.2 (15.10.94)\r\n"
#define VERSTAG	"\0$VER: Editor 1.2 (15.10.94)"
