/*
 *  Source machine generated by GadToolsBox V2.0
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Ari Tsironis
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_Activity                            0

#define GDX_Activity                           0

#define Sysop_CNT 1

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *SysopWnd;
extern struct Gadget        *SysopGList;
extern struct IntuiMessage   SysopMsg;
extern struct Gadget        *SysopGadgets[1];
extern UWORD                 SysopLeft;
extern UWORD                 SysopTop;
extern UWORD                 SysopWidth;
extern UWORD                 SysopHeight;
extern UBYTE                *SysopWdt;
extern struct MinList        Activity0List;
extern struct TextAttr       XEN9;
extern UWORD                 SysopGTypes[];
extern struct NewGadget      SysopNGad[];
extern ULONG                 SysopGTags[];

extern void ActivityClicked( int );
extern void PrintSysop(struct RastPort *);

extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern int HandleSysopIDCMP( void );
extern int OpenSysopWindow( void );
extern void CloseSysopWindow( void );
