                IFND    LIBRARIES_FAME_LIB_I
LIBRARIES_FAME_LIB_I    SET 1

                IFND EXEC_LIBRARIES_I
                        INCLUDE "exec/libraries.i"
                ENDC


                LIBINIT

                LIBDEF  _LVOFAMEStrStr
                LIBDEF  _LVOFAMEStackReport
                LIBDEF  _LVOFAMEStrChr
                LIBDEF  _LVOFAMEFileCopy
                LIBDEF  _LVOFAMEFSearch
                LIBDEF  _LVOFAMEIsNumStr
                LIBDEF  _LVOFAMEStrChrCase
                LIBDEF  _LVOFAMEStrFil
                LIBDEF  _LVOFAMEStrMid
                LIBDEF  _LVOFAMEStrStrCase
                LIBDEF  _LVOFAMEAllocPooled
                LIBDEF  _LVOFAMECreatePool
                LIBDEF  _LVOFAMEDeletePool
                LIBDEF  _LVOFAMEFreePooled
                LIBDEF  _LVOFAMEResetPool
                LIBDEF  _LVOFAMEFillMem
                LIBDEF  _LVOFAMEChrCut
                LIBDEF  _LVOFAMEChrCutCase
                LIBDEF  _LVOFAMEStrCut
                LIBDEF  _LVOFAMEStrCutCase
                LIBDEF  _LVOFAMEStrCopy
                LIBDEF  _LVOFAMEPrivate1
                LIBDEF  _LVOFAMEPrivate2
                LIBDEF  _LVOFAMEPrivate3
                LIBDEF  _LVOFAMEMemSet
                LIBDEF  _LVOFAMEPrivate4
                LIBDEF  _LVOFAMEPrivate5
                LIBDEF  _LVOFAMEPrivate6
                LIBDEF  _LVOFAMESwapRedWhite
                LIBDEF  _LVOFAMEAllocObject
                LIBDEF  _LVOFAMEFreeObject
                LIBDEF  _LVOFAMENumToStr
                LIBDEF  _LVOFAMEReverseLong
                LIBDEF  _LVOFAMEReverseWord
                LIBDEF  _LVOFAMEAdd64
                LIBDEF  _LVOFAMESub64
                LIBDEF  _LVOFAMEFreeDiskSpace
                LIBDEF  _LVOFAMEGetDevInfoList
                LIBDEF  _LVOFAMEFreeDevInfoList
                LIBDEF  _LVOFAMEStartECTimer
                LIBDEF  _LVOFAMEStopECTimer
                LIBDEF  _LVOFAMELoadFile
                LIBDEF  _LVOFAMEFreeFile
                LIBDEF  _LVOFAMEAvailExe
                LIBDEF  _LVOFAMEOverallBytes
                LIBDEF  _LVOFAMEDosMove
                LIBDEF  _LVOFAMEPostFile
                LIBDEF  _LVOFAMEStrToUpper
                LIBDEF  _LVOFAMEStrToLower
                LIBDEF  _LVOFAMEExecuteDir
                LIBDEF  _LVOFAMEFreeExecuteDirList
                LIBDEF  _LVOFAMELoadFilePooled
                LIBDEF  _LVOFAMENum64ToStr
                LIBDEF  _LVOFAMECutANSI
                LIBDEF  _LVOFAMEAtol
                LIBDEF  _LVOFAMEPrivate7
                LIBDEF  _LVOFAMEPrivate8
                LIBDEF  _LVOFAMEPrivate9
                LIBDEF  _LVOFAMEPrivate10
                LIBDEF  _LVOFAMEPrivate11
                LIBDEF  _LVOFAMEPrivate12
                LIBDEF  _LVOFAMEStrCat
                LIBDEF  _LVOFAMEPrivate13
                LIBDEF  _LVOFAMEPrivate14
                LIBDEF  _LVOFAMEPrivate15
                LIBDEF  _LVOFAMEPrivate16
                LIBDEF  _LVOFAMEIsEqual64
                LIBDEF  _LVOFAMEIsHigher64
                LIBDEF  _LVOFAMEIsLower64
                LIBDEF  _LVOFAMEMulU64L
                LIBDEF  _LVOFAMENum64Comp
                LIBDEF  _LVOFAMEStrTo64
                LIBDEF  _LVOFAMEGetObjectSize
                LIBDEF  _LVOFAMESPrintfA
                LIBDEF  _LVOFAMEDivU64L
                LIBDEF  _LVOFAMEObtainConfig
                LIBDEF  _LVOFAMEReleaseConfig
                LIBDEF  _LVOFAMERequestReset
                LIBDEF  _LVOFAMEReloadConfig
                LIBDEF  _LVOFAMESaveConfig
                LIBDEF  _LVOFAMESaveAllConfig
                LIBDEF  _LVOFAMELockConfig
                LIBDEF  _LVOFAMEAttemptLockConfig
                LIBDEF  _LVOFAMEUnLockConfig
                LIBDEF  _LVOFAMEHandleConfigResults
                LIBDEF  _LVOFAMEPrivate17
                LIBDEF  _LVOFAMEPrivate18
                LIBDEF  _LVOFAMEPrivate19

   ENDC         ; LIBRARIES_FAME_LIB_I
