/* $VER: Lightning.rexx v1.0
 *
 * Frontend script for Lightning Filelister (c)1996 Rod Schnell.
 *
 * Runs lightning to generate filelists, then archives files, copies both
 * archived and unarchived lists to file areas and updates file catalogues.
 *
 */

options results
options failat 21

signal on halt
signal on ioerr
signal on break_c

/**************************** CONFIGURATION **************************/

Area     = 1               /* Area number to upload files to                 */
AreaPath = 'File:TGFILES/' /* Full path to the area files are uploaded to    */
                           /* Requires trailing ':' or '/'                   */
TempDir  = 'File:'         /* Directory where lists output by Lightning are  */
                           /* to be found and where archives will be created */
                           /* Requires trailing ':' or '/'                   */

/* Input file names - must be the same as the files generated by Lightning   */
/*                    which are specified in Lightning.cfg                   */

InFile.1 = 'tgfiles.txt'
InFile.2 = 'tgnew.txt'
InFile.3 = 'tgfiles.ibm'
InFile.4 = 'tgnew.ibm'
InFile.5 = 'tgfiles.guide'
InFile.6 = 'tgnew.guide'

/* Output files - Archives generated by this script */

ArcFile.1 = 'tgfiles.lha'
ArcFile.2 = 'tgnew.lha'
ArcFile.3 = 'tgibm.zip'
ArcFile.4 = 'tgnewibm.zip'
ArcFile.5 = 'tgfilesguide.lha'
ArcFile.6 = 'tgnewguide.lha'

/* FileNotes (Descriptions) for Archived filelists (79 character maximum) */

FileNote.1 = 'Archived list of all files on The Guild BBS in Amiga text format'
FileNote.2 = 'Archived list of new files (30 days) on The Guild BBS in Amiga text format'
FileNote.3 = 'Archived list of all files on The Guild BBS in IBM text format'
FileNote.4 = 'Archived list of new files (30 days) on The Guild BBS in IBM text format'
FileNote.5 = 'Archived list of all files on The Guild BBS in AmigaGuide format'
FileNote.6 = 'Archived list of new files (30 days) on The Guild BBS in AmigaGuide format'

/*  You will also need to edit the path to Lightning (9 lines down)  */

/************************ END OF CONFIGURATION ***********************/

call Pragma('S',64000)
call Pragma('D',tempdir)

/* Run Lightning to create the unarchived lists */

address command 'Zeus:Developers/Mien/Lightning/Lightning'

/* Archive the lists */

address command 'lha -a -x -m r 'Tempdir||ArcFile.1' 'Tempdir||InFile.1
address command 'lha -a -x -m r 'Tempdir||ArcFile.2' 'Tempdir||InFile.2
address command 'zip -jkq9 'Tempdir||ArcFile.3' 'Tempdir||InFile.3
address command 'zip -jkq9 'Tempdir||ArcFile.4' 'Tempdir||InFile.4
address command 'lha -a -x -m r 'Tempdir||ArcFile.5' 'Tempdir||InFile.5
address command 'lha -a -x -m r 'Tempdir||ArcFile.6' 'Tempdir||InFile.6

/* Add filenotes (descriptions) to files */

address command 'filenote 'Tempdir||ArcFile.1' "'FileNote.1'"'
address command 'filenote 'Tempdir||ArcFile.2' "'FileNote.2'"'
address command 'filenote 'Tempdir||ArcFile.3' "'FileNote.3'"'
address command 'filenote 'Tempdir||ArcFile.4' "'FileNote.4'"'
address command 'filenote 'Tempdir||ArcFile.5' "'FileNote.5'"'
address command 'filenote 'Tempdir||ArcFile.6' "'FileNote.6'"'

/* Upload both archived and unarchived versions of the files */
/* Must first delete existing file so ZUploader will work    */

if exists(AreaPath||InFile.1)
	then Address command 'delete 'AreaPath||InFile.1
Address Command 'Zeus:Bin/ZUploader FILE 'Tempdir||InFile.1' AREA 'area' UPLOADER Lightning REPLACE'
if exists(AreaPath||InFile.2)
	then Address command 'delete 'AreaPath||InFile.2
Address Command 'Zeus:Bin/ZUploader FILE 'Tempdir||InFile.2' AREA 'area' UPLOADER Lightning REPLACE'
if exists(AreaPath||InFile.3)
	then Address command 'delete 'AreaPath||InFile.3
Address Command 'Zeus:Bin/ZUploader FILE 'Tempdir||InFile.3' AREA 'area' UPLOADER Lightning REPLACE'
if exists(AreaPath||InFile.4)
	then Address command 'delete 'AreaPath||InFile.4
Address Command 'Zeus:Bin/ZUploader FILE 'Tempdir||InFile.4' AREA 'area' UPLOADER Lightning REPLACE'
if exists(AreaPath||InFile.5)
	then Address command 'delete 'AreaPath||InFile.5
Address Command 'Zeus:Bin/ZUploader FILE 'Tempdir||InFile.5' AREA 'area' UPLOADER Lightning REPLACE'
if exists(AreaPath||InFile.6)
	then Address command 'delete 'AreaPath||InFile.6
Address Command 'Zeus:Bin/ZUploader FILE 'Tempdir||InFile.6' AREA 'area' UPLOADER Lightning REPLACE'

if exists(AreaPath||ArcFile.1)
	then Address command 'delete 'AreaPath||ArcFile.1
Address Command 'Zeus:Bin/ZUploader FILE 'Tempdir||ArcFile.1' AREA 'area' UPLOADER Lightning REPLACE'
if exists(AreaPath||ArcFile.2)
	then Address command 'delete 'AreaPath||ArcFile.2
Address Command 'Zeus:Bin/ZUploader FILE 'Tempdir||ArcFile.2' AREA 'area' UPLOADER Lightning REPLACE'
if exists(AreaPath||ArcFile.3)
	then Address command 'delete 'AreaPath||ArcFile.3
Address Command 'Zeus:Bin/ZUploader FILE 'Tempdir||ArcFile.3' AREA 'area' UPLOADER Lightning REPLACE'
if exists(AreaPath||ArcFile.4)
	then Address command 'delete 'AreaPath||ArcFile.4
Address Command 'Zeus:Bin/ZUploader FILE 'Tempdir||ArcFile.4' AREA 'area' UPLOADER Lightning REPLACE'
if exists(AreaPath||ArcFile.5)
	then Address command 'delete 'AreaPath||ArcFile.5
Address Command 'Zeus:Bin/ZUploader FILE 'Tempdir||ArcFile.5' AREA 'area' UPLOADER Lightning REPLACE'
if exists(AreaPath||ArcFile.6)
	then Address command 'delete 'AreaPath||ArcFile.6
Address Command 'Zeus:Bin/ZUploader FILE 'Tempdir||ArcFile.6' AREA 'area' UPLOADER Lightning REPLACE'

Exit

/* Error Handling */
halt:
ioerr:
break_c:
exit 10

