
BOOL __asm __saveds   HBBS_InitNode(register __d0 int N_NodeNum);
void __asm __saveds   HBBS_CleanUpNode( void );
BOOL __asm __saveds   HBBS_InitDoor( register __d0 int N_NodeNum, register __a0 char *name);
void __asm __saveds   HBBS_CleanUpDoor( void );
void __asm __saveds   ConWriteData(register __a0 UBYTE *data,register __d0 ULONG length);
void __asm __saveds   ConWriteStr(register __a0 UBYTE *data);
void __asm __saveds   AbortConRead( void );
void __asm __saveds   SendConReadData( void );
void __asm __saveds   ConReadData(register __d0 ULONG Length ); // make DAMN sure that length is NEVER more that the buffer size!
void __asm __saveds   ConWaitData( void );
void __asm __saveds   AbortSerRead( void );
void __asm __saveds   SendSerReadData( void );
void __asm __saveds   SerWaitData( void );
void __asm __saveds   SendSerReadBlock(register __a0 UBYTE *data,register __d0 ULONG length );
void __asm __saveds   WaitSerReadBlock(register __a0 UBYTE *data,register __d0 ULONG length );
ULONG __asm __saveds  SerQueryData( void );
V_BOOL __asm __saveds CarrierLost( void );
BOOL __asm __saveds   SerWriteDataWithTimeout(register __a0 UBYTE *data,register __d0 ULONG length,register __d1 ULONG Seconds,register __d2 ULONG Micros);
void __asm __saveds   SerWriteData(register __a0 UBYTE *data,register __d0 ULONG length);
BOOL __asm __saveds   SerWriteStrWithTimeout(register __a0 UBYTE *str,register __d0 ULONG Seconds,register __d1 ULONG Micros);
void __asm __saveds   SerWriteStr(register __a0 UBYTE *str);
void __asm __saveds   SerDelayWriteStr(register __a0 UBYTE *str);
void __asm __saveds   SerWriteChar(register __d0 UBYTE c);
void __asm __saveds   PutText(register __a0 UBYTE *str);
void __asm __saveds   PutData(register __a0 UBYTE *data,register __d0 ULONG Length);
void __asm __saveds   PutChar(register __d0 UBYTE ch);
void __asm __saveds   PutConText(register __a0 UBYTE *str);
void __asm __saveds   PutConData(register __a0 UBYTE *data,register __d0 ULONG Length);
void __asm __saveds   PutConChar(register __d0 UBYTE ch);
ULONG __asm __saveds  SetupConSerSigs( void );
ULONG __asm __saveds  HandleConSigs(register __d0 ULONG ReturnedSigs);
ULONG __asm __saveds  HandleSerSigs(register __d0 ULONG ReturnedSigs);
ULONG __asm __saveds  HandleConSerSigs(register __d0 ULONG ReturnedSigs);
void __asm __saveds   DOOR_SysopText(register __a0 UBYTE *str);
void __asm __saveds   DOOR_WriteText(register __a0 UBYTE *str);
void __asm __saveds   DOOR_WriteSerText(register __a0 UBYTE *str);
ULONG __asm __saveds  DOOR_GetLine(register __d0 ULONG Flags, register __d1 char PasswordChar,register __d2 ULONG MaxLen,register __d3 ULONG Timeout,register __a0 UBYTE *PromptStr);
void __asm __saveds   DOOR_UpdateNodeStatus(register __d0 ULONG What);
V_BOOL __asm __saveds DOOR_SystemDoor(register __a0 UBYTE *doorname,register __a1 UBYTE *options);
V_BOOL __asm __saveds DOOR_UserDoor(register __a0 UBYTE *doorname,register __a1 UBYTE *options);
void __asm __saveds   DOOR_HangUp( void );
void __asm __saveds   DOOR_Return( register __a0 UBYTE *returnstring );
V_BOOL __asm __saveds DOOR_DisplayScreen( register __a0 UBYTE *screenname );
V_BOOL __asm __saveds DOOR_DisplaySpecialScreen( register __a0 UBYTE *screenname );
V_BOOL __asm __saveds DOOR_PausePrompt( register __a0 UBYTE *prompt );
void __asm __saveds   DOOR_Add_Last_Upload( register __a0 UBYTE *details );
V_BOOL __asm __saveds DOOR_ContinuePrompt( register __a0 UBYTE *prompt,register __d0 V_BIGNUM Flags );
void __asm __saveds   DOOR_MenuPrompt(register __a0 char *promptstr,register __d0 char promptdefault);
void __asm __saveds   DOOR_Continue( register __d0 V_BOOL Continue );
V_BOOL __asm __saveds ValidConfNum(register __d0 V_BIGNUM ConfNum);
struct ConfData
      __asm __saveds *FindConf( void );
void  __asm __saveds  LoadAccess( register __a0 char *filename, register __a1 struct AccessData *AD);
char __asm __saveds  *HBBS_ModifyString(register __a0 char *str);
void __asm __saveds   HBBS_SetAccess( void );
V_BOOL __asm __saveds HBBS_CheckAccess(register __d0 ULONG AccessOption);
void __asm __saveds   HBBS_AddToCallersLog(register __a0 UBYTE *String);
struct TaggedFile
      __asm __saveds *HBBS_FindTag(register __a0 UBYTE *FileName,register __d0 BOOL MatchALL);
void __asm __saveds   HBBS_SetBBSCols( void );
V_BOOL __asm __saveds HBBS_LoadConfAcs( register __a0 struct ConfAcsData *ConfAcs, register __a1 char *filename);
V_BOOL __asm __saveds DOOR_CheckRaw(register __d0 ULONG Flags);
LONG __asm __saveds HBBS_TimeOnline( void );
LONG __asm __saveds HBBS_TimeLeft( void );
void __asm __saveds DOOR_Goodbye( void );
BOOL __asm __saveds HBBS_AllowConfAccess(register __d0 V_BIGNUM confnum,register __a0 struct UserData *User);
void __asm __saveds HBBS_SetBBSStrings( void );
void __asm __saveds HBBS_CleanupNodeConsoleWin( void );
void __asm __saveds HBBS_SetWatchTitles( void );
V_BOOL __asm __saveds HBBS_OpenNodeConsoleWin( void );
void __asm __saveds HBBS_ChangeConsoleMode( register __d0 short Mode ); // do NOT use this!!!!
void __asm __saveds DOOR_ChangeConsoleMode( register __d0 short Mode ); // use this from a door instead
void __asm __saveds DOOR_Add_Last_Download( register __a0 UBYTE *details );
V_BOOL __asm __saveds DOOR_AContinuePrompt( register __a0 UBYTE *prompt,register __d0 V_BIGNUM Flags,register __d1 ULONG Timeout);
V_BOOL __asm __saveds DOOR_CheckCSI( register __d0 char keychar,register __d1 short wherefrom );
void __asm __saveds DOOR_Add_Last_Pager( register __a0 UBYTE *details );
void __asm __saveds DOOR_Add_Last_PWFail( register __a0 UBYTE *details );
void __asm __saveds DOOR_Add_Last_Carrier( register __a0 UBYTE *details );
V_BOOL __asm __saveds DOOR_DisplayBulletin( register __a0 UBYTE *BulletinName );
