#pragma libcall HBBSNodeBase HBBS_InitNode 1e 001
#pragma libcall HBBSNodeBase HBBS_CleanUpNode 24 0
#pragma libcall HBBSNodeBase HBBS_InitDoor 2a 8002
#pragma libcall HBBSNodeBase HBBS_CleanUpDoor 30 0
#pragma libcall HBBSNodeBase ConWriteData 36 0802
#pragma libcall HBBSNodeBase ConWriteStr 3c 801
#pragma libcall HBBSNodeBase AbortConRead 42 0
#pragma libcall HBBSNodeBase SendConReadData 48 0
#pragma libcall HBBSNodeBase ConReadData 4e 001
#pragma libcall HBBSNodeBase ConWaitData 54 0
#pragma libcall HBBSNodeBase AbortSerRead 5a 0
#pragma libcall HBBSNodeBase SendSerReadData 60 0
#pragma libcall HBBSNodeBase SerWaitData 66 0
#pragma libcall HBBSNodeBase SendSerReadBlock 6c 0802
#pragma libcall HBBSNodeBase WaitSerReadBlock 72 0802
#pragma libcall HBBSNodeBase SerQueryData 78 0
#pragma libcall HBBSNodeBase CarrierLost 7e 0
#pragma libcall HBBSNodeBase SerWriteDataWithTimeout 84 210804
#pragma libcall HBBSNodeBase SerWriteData 8a 0802
#pragma libcall HBBSNodeBase SerWriteStrWithTimeout 90 10803
#pragma libcall HBBSNodeBase SerWriteStr 96 801
#pragma libcall HBBSNodeBase SerDelayWriteStr 9c 801
#pragma libcall HBBSNodeBase SerWriteChar a2 001
#pragma libcall HBBSNodeBase PutText a8 801
#pragma libcall HBBSNodeBase PutData ae 0802
#pragma libcall HBBSNodeBase PutChar b4 001
#pragma libcall HBBSNodeBase PutConText ba 801
#pragma libcall HBBSNodeBase PutConData c0 0802
#pragma libcall HBBSNodeBase PutConChar c6 001
#pragma libcall HBBSNodeBase SetupConSerSigs cc 0
#pragma libcall HBBSNodeBase HandleConSigs d2 001
#pragma libcall HBBSNodeBase HandleSerSigs d8 001
#pragma libcall HBBSNodeBase HandleConSerSigs de 001
#pragma libcall HBBSNodeBase DOOR_SysopText e4 801
#pragma libcall HBBSNodeBase DOOR_WriteText ea 801
#pragma libcall HBBSNodeBase DOOR_WriteSerText f0 801
#pragma libcall HBBSNodeBase DOOR_GetLine f6 8321005
#pragma libcall HBBSNodeBase DOOR_UpdateNodeStatus fc 001
#pragma libcall HBBSNodeBase DOOR_SystemDoor 102 9802
#pragma libcall HBBSNodeBase DOOR_UserDoor 108 9802
#pragma libcall HBBSNodeBase DOOR_HangUp 10e 0
#pragma libcall HBBSNodeBase DOOR_Return 114 801
#pragma libcall HBBSNodeBase DOOR_DisplayScreen 11a 801
#pragma libcall HBBSNodeBase DOOR_DisplaySpecialScreen 120 801
#pragma libcall HBBSNodeBase DOOR_PausePrompt 126 801
#pragma libcall HBBSNodeBase DOOR_Add_Last_Upload 12c 801
#pragma libcall HBBSNodeBase DOOR_ContinuePrompt 132 0802
#pragma libcall HBBSNodeBase DOOR_MenuPrompt 138 0802
#pragma libcall HBBSNodeBase DOOR_Continue 13e 001
#pragma libcall HBBSNodeBase ValidConfNum 144 001
#pragma libcall HBBSNodeBase FindConf 14a 0
#pragma libcall HBBSNodeBase LoadAccess 150 9802
#pragma libcall HBBSNodeBase HBBS_ModifyString 156 801
#pragma libcall HBBSNodeBase HBBS_SetAccess 15c 0
#pragma libcall HBBSNodeBase HBBS_CheckAccess 162 001
#pragma libcall HBBSNodeBase HBBS_AddToCallersLog 168 801
#pragma libcall HBBSNodeBase HBBS_FindTag 16e 0802
#pragma libcall HBBSNodeBase HBBS_SetBBSCols 174 0
#pragma libcall HBBSNodeBase HBBS_LoadConfAcs 17a 9802
#pragma libcall HBBSNodeBase DOOR_CheckRaw 180 001
#pragma libcall HBBSNodeBase HBBS_TimeOnline 186 0
#pragma libcall HBBSNodeBase HBBS_TimeLeft 18c 0
#pragma libcall HBBSNodeBase DOOR_Goodbye 192 0
#pragma libcall HBBSNodeBase HBBS_AllowConfAccess 198 8002
#pragma libcall HBBSNodeBase HBBS_SetBBSStrings 19e 0
#pragma libcall HBBSNodeBase HBBS_CleanupNodeConsoleWin 1a4 0
#pragma libcall HBBSNodeBase HBBS_SetWatchTitles 1aa 0
#pragma libcall HBBSNodeBase HBBS_OpenNodeConsoleWin 1b0 0
#pragma libcall HBBSNodeBase HBBS_ChangeConsoleMode 1b6 001
#pragma libcall HBBSNodeBase DOOR_ChangeConsoleMode 1bc 001
#pragma libcall HBBSNodeBase DOOR_Add_Last_Download 1c2 801
#pragma libcall HBBSNodeBase DOOR_AContinuePrompt 1c8 10803
#pragma libcall HBBSNodeBase DOOR_CheckCSI 1ce 1002
#pragma libcall HBBSNodeBase DOOR_Add_Last_Pager 1d4 801
#pragma libcall HBBSNodeBase DOOR_Add_Last_PWFail 1da 801
#pragma libcall HBBSNodeBase DOOR_Add_Last_Carrier 1e0 801
#pragma libcall HBBSNodeBase DOOR_DisplayBulletin 1e6 801
