

Your account has now come up for Review by the SystemOperators.
With this being the case your access has been removed from the
system until a suitable conclusion has been determined from
your support of the BBS.

The line will now be terminated and your account will be dealt
with as soon as possible.

%TC=1.ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ%TC=3. Terminate Call%TC=1. >>%TC=7.


