%TC=7.
Your account will come up for Review by the system operator on %BOLD=1.%TC=1.%REVIEW.%BOLD=0.%TC=7..
Your account will be checked for support of the BBS overall and dealt with
accordingly. Please make sure that you have contributed to the overall
running of the system to carry on using your account.

%TC=1.ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ%TC=3. Terminate Call%TC=1. >>%TC=7.

    GoodBye...

