%CLS.%CURSOR=0.%BC=0.%TC=7.
  %BC=4.%TC=4.€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€%BC=0.
  %BC=4.€€%TC=7.Menu Selector%BC=0.%TC=4.€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€%BC=0.
  €ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ€ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ€%BC=0.
  €  %TC=6.[%TC=7.B%TC=6.] Button Menus               %TC=3.     %TC=4.€  %TC=6.[%TC=7.C%TC=6.] Command Menus               %TC=4.%BC=7.€%BC=0.
  €  %TC=6.[%TC=7.H%TC=6.] Hotkey Menus               %TC=3.     %TC=4.€  %TC=6. %TC=7. %TC=6.                              %TC=4.%BC=7.€%BC=0.
  ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ
%BC=0.%TC=7.%CURSOR=1.
 ...Button Menus are cursor driven. Your terminal MUST support ANSI.

 ...HotKey Menus are the 'old' style plain menus.

 ...Command Menus are Command Line driven. Very powerful, for the experienced!

