;* ASM Includefile generated by RevUp 1.2 *

VERSION		EQU	3
REVISION	EQU	1
DATE	MACRO
		dc.b	'22.7.95'
	ENDM
VERS	MACRO
		dc.b	'wwbbsaux-handler 3.1'
	ENDM
VSTRING	MACRO
		dc.b	'wwbbsaux-handler 3.1 (22.7.95)',13,10,0
	ENDM
VERSTAG	MACRO
		dc.b	0,'$VER: wwbbsaux-handler 3.1 (22.7.95)',0
	ENDM
