Hacker v4.0 - Originaly by Patrick Baker, modified by Bob Maple

	Please report any bugs to The Back Burner BBS, 303-697-1225 (2400)
        or 303-697-8156 (v.42/v.42bis--HST), or write to P.O. Box 22, Morrison
        CO, 80465.  For updates, call The Back Burner BBS.

	This PFile and all it's files and modules are authorized to be run
	on LEGAL C-Net AMIGA systems only.  It is to only be re-distributed
	to other legal owners, in it's original archive, with no modifications
	present.  You may modify this file however you like for your own
	personal use but it must be distributed in it's original form.

	I do not claim the fame on this game.  As said, this game was orignaly
        written by Patrick Baker, and I merely optimized it and modified it.

 TO USE:

 First off, let me start out by saying that this game is significantly smaller
 than when it was in it's original state; that would be v2.5.  It is now about
 half of it's original size, so a lot more people should be able to use it.
 In my own experiments, I've found that the program takes about 320k to run
 totaly; it starts out as less but the more you play the more it takes.  So if
 you don't have that much memory free when all your BBS junk is loaded, then
 stop right here.  I'm not sure exactly how to make it a little more memory
 stingy, but significantly reducing the size of the game has helped.

---

 Start off by deciding where you want this to go.  After you do that,
 copy "Hacker4.0", and the Hacker directory to wherever you decided.
 Then, add it in the corresponding PFiles directory:

 Title of item  : Hacker4.0
 Subdirectory?  : No
 PROGRAM file?  : Yes
 AREXX program? : Yes
 Access   (all) : **This is up to you**
 Description    : Hacker v4.0
 Date +/-/*=now :
 Days to keep   :
 MCI environ (0):
 Exclusive use? : Yes

 After you do that, load up your favorite text editor and load up the
 HACKER4.0 main file. You're going to have to edit some pathnames.
 You should see:

 save   = 'PFiles:MultiPlayer/Hacker/'  /*  Main path for all Hacker files  */
 play   = save'Players/'                /*  Where user files are stored     */

 plus a bunch of more lines of paths and stuff.  You only need to edit the
 first one (save), and direct Hacker where to look for it's files.  NOTE:
 If you are putting it inside a directory, the path MUST end in a '/'!  In
 other words, if it was just PFILES:, thats ok.. but PFILES:Games is not;
 it must be PFILES:Games/.  You also need to edit the "minbytes" variable
 at the end of all the pathnames.  This is the amount of memory in bytes that
 MUST be free at all times while the game is running.. This just gives you
 a little leeway so that normal BBS operations have memory to run (like
 other ports, for example).

 Thats all there is to it.  PLEASE call my BBS or write and report any bugs
 you have found, what you did to cause them, or any options you would like
 to see put in.
 
 Now go read the docs so you know a little how the game works, and what you
 can and cannot do to it. (SysopDocs.TXT in the Hacker directory)

    -Bob Maple/The Brazilian

     303-697-1225, 24Hrs, 300-2400MNP
     303-697-8156, 24Hrs, 2400-9600HST
