/**/

ADDRESS "SERVER-REXX"
OPTIONS RESULTS

NODE = 2

	NODEINFO NODE 0 			/* QUERY NODE ACTIVITY */
	IF RC=0 THEN do; SAY "Node "NODE" is not active!"; exit; end

							/* NODE IS ACTIVE */
	NODEINFO NODE 1			/* QUERY IF USER IS ONLINE */
	IF RC=0 THEN do; SAY "No user online on node #"NODE"."; exit; end

							/* THERE IS A USER ONLINE */

	NODEINFO NODE 6 		/* QUERY USER ORGANIZATION */
	ORGANIZATION=RESULT

	NODEINFO NODE 5 		/* QUERY USER LOCATION */
	LOCATION=RESULT

	NODEINFO NODE 4 		/* QUERY USER REALNAME */
	REALNAME=RESULT

	NODEINFO NODE 3 		/* QUERY USER HANDLE */
	HANDLE=RESULT

	NODEINFO NODE 2 		/* QUERY ACTIVITY STRING */
	ACTIVITY=RESULT

	SAY HANDLE
	SAY REALNAME
	SAY LOCATION
	SAY ORGANIZATION
	SAY ACTIVITY

EXIT 0
