/* $VER: Lightning.rexx v1.1 (28.Apr.96)
 *
 * Frontend script for Lightning Filelister (c)1996 Rod Schnell.
 *
 * v1.1 - Added some rudimentary error checking and handling.
 *      - No longer uses Zuploader.
 *
 * Runs lightning to generate filelists, then archives files, copies both
 * archived and unarchived lists to file areas and updates file catalogues.
 *
 */

options results
options failat 21

signal on halt
signal on ioerr
signal on break_c

/**************************** CONFIGURATION **************************/

Area     = 1               /* Area number to upload files to                 */
AreaPath = 'File:TGFILES/' /* Full path to the area files are uploaded to    */
                           /* Requires trailing ':' or '/'                   */
TempDir  = 'File:'         /* Directory where lists output by Lightning are  */
                           /* to be found and where archives will be created */
                           /* Requires trailing ':' or '/'                   */

numfiles = 6               /* Total Number of original (unarchived) files    */
                           /* to process                                     */

arcfiles = 1               /* archive files 1 = yes 0 = no                   */

/* Input file names - must be the same as the files generated by Lightning   */
/*                    which are specified in Lightning.cfg                   */

InFile.1 = 'tgfiles.txt'
InFile.2 = 'tgnew.txt'
InFile.3 = 'tgfiles.ibm'
InFile.4 = 'tgnew.ibm'
InFile.5 = 'tgfiles.guide'
InFile.6 = 'tgnew.guide'

/* Output files - Archives generated by this script */

ArcFile.1 = 'tgfiles.lha'
ArcFile.2 = 'tgnew.lha'
ArcFile.3 = 'tgibm.zip'
ArcFile.4 = 'tgnewibm.zip'
ArcFile.5 = 'tgfilesguide.lha'
ArcFile.6 = 'tgnewguide.lha'

/* FileNotes (Descriptions) for Archived filelists (79 character maximum) */
/* Unarchived files allready have filenote descriptions                   */

FileNote.1 = 'Archived list of all files on The Guild BBS in Amiga text format'
FileNote.2 = 'Archived list of new files (30 days) on The Guild BBS in Amiga text format'
FileNote.3 = 'Archived list of all files on The Guild BBS in IBM text format'
FileNote.4 = 'Archived list of new files (30 days) on The Guild BBS in IBM text format'
FileNote.5 = 'Archived list of all files on The Guild BBS in AmigaGuide format'
FileNote.6 = 'Archived list of new files (30 days) on The Guild BBS in AmigaGuide format'

/*  You will also need to edit the path to Lightning (10 lines down)  */
/*  You may also wish to edit the archive commands used below        */

/************************ END OF CONFIGURATION ***********************/

call Pragma('S',64000)
call Pragma('D',tempdir)

/* Run Lightning to create the unarchived lists */

address command 'Zeus:Developers/Mien/Lightning/Lightning'
say ''

if arcfiles = 1 then do

	/* Archive the filelists */

	if exists(TempDir||InFile.1) then 
		address command 'lha -a -x -m r 'Tempdir||ArcFile.1' 'Tempdir||InFile.1
	if exists(TempDir||InFile.2) then 
		address command 'lha -a -x -m r 'Tempdir||ArcFile.2' 'Tempdir||InFile.2
	if exists(TempDir||InFile.3) then 
		address command 'zip -jkq9 'Tempdir||ArcFile.3' 'Tempdir||InFile.3
	if exists(TempDir||InFile.4) then 
		address command 'zip -jkq9 'Tempdir||ArcFile.4' 'Tempdir||InFile.4
	if exists(TempDir||InFile.5) then 
		address command 'lha -a -x -m r 'Tempdir||ArcFile.5' 'Tempdir||InFile.5
	if exists(TempDir||InFile.6) then 
		address command 'lha -a -x -m r 'Tempdir||ArcFile.6' 'Tempdir||InFile.6
end

upall:

Address 'ZEUS'

i = 0
do until i = numfiles
	i = i + 1

	/* Upload original (unarchived) files */

	FileName    = InFile.i
	FilePath    = Tempdir||InFile.i
	AreaNumber  = Area
	Description = ''

	if exists(TempDir||InFile.i) then call UpFile

	if arcfiles = 1 then do

		/* Add filenotes (descriptions) to archived files */

		address command 'filenote 'Tempdir||ArcFile.i' "'FileNote.i'"'
		
		/* Upload archived files */

		FileName    = ArcFile.i
		FilePath    = Tempdir||ArcFile.i
		AreaNumber  = Area
		Description = FileNote.i

		if exists(TempDir||ArcFile.i) then call UpFile
	end
end

exit

UpFile:

say ''

GetFileArea '"'AreaNumber'"' 'Number'
if RC = 0 then do
	GetFile NAME '"'FileName'"' 'FileNumber'
	if RC ~= 0 then do 
		say 'Uploading 'FileName' to area 'AreaNumber
		if description = '' then description = substr(statef( FilePath ), wordindex( statef( FilePath ), 8))
		AddFile '"'FilePath'"' '"'AreaNumber'"' 'DESCRIPTION' '"'Description'"'
		select
			when RC = 0 then say 'File saved OK!'
			when RC = 1 then say 'Error saving 'FileName' - 'RESULT
			when RC = 2 then say 'Could not move file!'
			when RC = 3 then say 'Bad description!'
			when RC = 4 then say 'Could not access file!'
			when RC = 6 then say 'Could not add file, no available paths for upload.'
			otherwise say 'Fatal error! Is Zeus running?'
		end
	end

	else do
		FileNumber = Result
		GetFileArea '"'AreaNumber'"' 'Path'
		SavePath = result
		say 'Updating 'FileName' in area 'AreaNumber
		address command 'copy 'FilePath' TO "'SavePath'" CLONE'
		if RC = 0 then say 'Copied 'FilePath' TO 'SavePath
		else do
			say 'Copy 'FilePath' TO 'SavePath' failed!'
			return
		end
		dfsize = word( statef( SavePath||FileName ), 2)
		EditFile NUMBER FileNumber SIZE dfsize
		if RC = 0 then say 'Updated filesize 'dfsize
		else say 'Failed to update filesize!'
	end
end
else say 'Invalid upload area number!'
return

/* Error Handling */
halt:
ioerr:
break_c:
exit 21
