/* 

                       Kicker's Advertising Arexx Pfile
                     Made to work with Cnet3 - Nov-03-1994
                          This file is DonationWare. 
                   Please send me $10 if you use this file.
                               Send to:

                               Leo Anderson Jr.
                               P.O. Box 56
                               Laporte, Mn
                               56461

            I don't usually beg for cash,  but I'm broke and
           out of HD space. 8( So if you use this to make some
           extra cash for your board, please send me the $10 in cash,
           money order, check, sand-dollars, velvet paintings of
           Elvis using the Amiga (please don't), or any other thing
           worth $10. <G>

         I am not responsible for any damage that may result from this
         file to your computer, your aunt Selma, your chances with the
         redhead down the hall or anything else.  It's only an arexx 
         ad file, what damage could it do.

            Please do not edit this file and then distribute it.  

          If you need to contact me for anything I can be reached by:

                BBS : Kicker's Hole BBS (218) 224-2926
           Internet : kicker@chefnet.edu (a local BBS)
        Voice Phone : (218) 224-2936
          Rocketnet : Kicker@10:218/0.0
      Smoke Signals : 2 big puffs, 3 small puffs, 5 big puffs.

       This file was brought to you by the letter A & Z and the number 5
*/

options results

GETUSER 39
usernum=result

/* Paths */

path = 'mail:users/'/* <= put your users path in here */
path1 = 'cnet:ads/' /* <= put your ad path in here */

/* Number of Ads */

noa = 3             /* <--  put the number of ads that you have here
                            noa = Number Of Ads <G> 
                            Name all your ads : ad.1 ad.2 etc....*/



if ~exists(path''usernum'/_kad') then call first
main:
call open(user,path''usernum'/_kad','R')
en=readln(user)
call close user
if en = noa then en = 0
if en > noa then en = 0
en = en + 1
sendfile path1'ad.'en
 open(user,path''usernum'/_kad','W')
 writeln(user,en)
 call close user
exit

first:
 open(user,path''usernum'/_kad','W')
 en = 0
 writeln(user,en)
call close user
call main
end
exit
