
                             » SYSTEM USERS MENU «

  A - File Flags            N - Neue Files seit...   F - Kompl. File Liste
  B - Bulletins             O - Page Sysop !         U - UPLOAD! Files
  C - Message to Sysop      R - Read E-Mail          V - Show a Textfile
  D - Download Files        S - Show your Stats.     W - Show your Defaults
  E - Enter E-Mail          T - Time & Date          Z - Search for File Names
  G - LOGOFF (See Ya!)      H - Need Help ?!         J - Join Conference
  I - B.B.S. Info           L - Last Callers         K - Other Node callers
  M - Ansi On/Off           UR - Upload Resume       DR - Download Resume

            ZOOM - Zoo Mail (For Off-Line reading) » Free Download «

