.-------------------------------------------------------------------------.
|A - File Flags            N - Neue Files seit...   F - Kompl. File Liste |
|B - Bulletins             O - Page Sysop !         U - UPLOAD! Files     |
|C - Mail an Sysop lassen  R - Mail lesen           V - Textfile anzeigen |
|D - Download Files        S - Status anschauen     W - User Settings     |
|E - Mail schreiben        T - Zeit & Datum         Z - Filesuche         |
|G - LOGOFF (See Ya!)      H - Hilfe                J - Area Wechseln     |
|I - B.B.S. Info           $ - Nochmal Mail Scannen                       |
|M - Ansi Ein/Aus        WHO - Wer is aufm Andern Port                    |
|           ZOOM - Zoo Mail (For Off-Line reading) » Free Download «      |
`-------------------------------------------------------------------------'

