.key NodeNum,UserID
.bra [
.ket ]

;echo >>T:LogOffScriptTest.TXT "UserID: [UserID] Name: $HNode[NodeNum]User just logged off Node [NodeNum] at " NOLINE
;date >>T:LogOffScriptTest.TXT
;
;
; The above example script file will create a file in t: with each line looking
; something like this
;
; UserID: 1 Name: Hydra just logged off Node 3 at Wednesday 03-Jan-96 21:53:32

; Create LastCallers screen

HBBS:Utils/LastCallers UPDATE [NodeNum] CREATE HBBS:Nodes/Node[NodeNum]/Screens/Special/LastCallers.TXT 20 ALLNODES INCLUDELOCAL

; Create some bulletins/stats screens
HBBS:Utils/HBBSMultiTop >nil: hbbs:Utils/HBBSMultiTop_MTs/TopByteUploader_1.mt HBBS:Screens/Misc/TBU.TXT hbbs:Utils/HBBSMultiTop_MTs/TopFileUploader_1.mt HBBS:Screens/Misc/TFU.TXT hbbs:Utils/HBBSMultiTop_MTs/TopFileDownloader_1.mt HBBS:Screens/Misc/TFD.TXT hbbs:Utils/HBBSMultiTop_MTs/TopByteDownloader_1.mt HBBS:Screens/Misc/TBD.TXT hbbs:Utils/HBBSMultiTop_MTs/BestByteUploader_1.mt HBBS:Screens/Misc/BBU.TXT