/*pragma libcall SerTransBase Private1 1e 0*/
/*pragma libcall SerTransBase Private2 24 0*/
/*pragma libcall SerTransBase Private3 2a 0*/
/*pragma libcall SerTransBase Private4 30 0*/
/*pragma libcall SerTransBase Private5 36 0*/
/*pragma libcall SerTransBase Private6 3c 0*/
#pragma libcall SerTransBase ST_OpenSerTrans 42 001
#pragma libcall SerTransBase ST_CloseSerTrans 48 001
#pragma libcall SerTransBase ST_Send 4e 8002
#pragma libcall SerTransBase ST_Read 54 A984321008
#pragma libcall SerTransBase ST_CursorInput 5a 81003
#pragma libcall SerTransBase ST_ReceiveFile 60 8002
#pragma libcall SerTransBase ST_SendFile 66 8002
#pragma libcall SerTransBase ST_Logoff 6c 001
#pragma libcall SerTransBase ST_OutKick 72 8002
/*pragma libcall SerTransBase Private7 78 0*/
/*pragma libcall SerTransBase Private8 7e 0*/
#pragma libcall SerTransBase ST_CheckCarrier 84 001
#pragma libcall SerTransBase ST_ConPutString 8a 8002
#pragma libcall SerTransBase ST_SerPutString 90 8002
#pragma libcall SerTransBase ST_WriteProtocol 96 8002
#pragma libcall SerTransBase ST_GetChar 9c 001
#pragma libcall SerTransBase ST_HorizCursorInput a2 8002
