   IFND  LIBRARIES_PIPELINE_I
LIBRARIES_PIPELINE_I  SET   1
**
** $VER: pipeline.i 37.0 (04.05.93)
**
** Useful definitions for pipeline.library
**
** (C) Copyright 1992-1993 Alex May & Nick Loman.
** All rights reserved.
**

    IFND EXEC_TYPES_I
    INCLUDE "exec/types.i"
    ENDC ; EXEC_TYPES_I

*
* The function description struct
*

	STRUCTURE	FD,0
	APTR			FD_COMMAND
	APTR			FD_FUNCTION
	APTR			FD_PRIV1
	APTR			FD_PRIV2
*	ULONG			FD_FLAGS				* Proposed addition
	LABEL			FD_SIZE

*
* CC Args
*

	STRUCTURE	CCArgs,0
	APTR			cc_Line
	ULONG			cc_Code
	ULONG			cc_MaxLen
	APTR			cc_Buffer
	STRUCT		cc_Args,40
	STRUCT		cc_Format,30
	LABEL			cc_SIZE

*
* The user structure
*

	STRUCTURE	UR,0
	STRUCT		UR_NAME,40
	STRUCT		UR_ALIAS,40
	STRUCT		UR_PASSWORD,20
	STRUCT		UR_VOICEPHONE,20
	STRUCT		UR_DATAPHONE,20
	STRUCT		UR_STREET,40
	STRUCT		UR_TOWN,20
	STRUCT		UR_COUNTY,20
	STRUCT		UR_POSTCODE,12
	STRUCT		UR_COUNTRY,20
	LONG			UR_FIRSTCALL
	LONG			UR_LASTCALL
	ULONG			UR_LASTBAUDRATE
	ULONG			UR_FLAGS
	UBYTE			UR_RIPFSZ
	UBYTE			UR_UNUSED
	UWORD			UR_EXTFLAGS
	LONG			UR_CREDIT
	UWORD			UR_MINSLEFT
	UWORD			UR_NUMCALLS
	UWORD			UR_MAXCALLSPERDAY
	UWORD			UR_MAXMINSPERCALL
	UWORD			UR_MAXMINSPERDAY
	UWORD			UR_DOB_YEAR
	UBYTE			UR_DOB_MON
	UBYTE			UR_DOB_DAY
	UBYTE			UR_ACCESS
	UBYTE			UR_COMPUTER
	UBYTE			UR_SCRWIDTH
	UBYTE			UR_SCRHEIGHT
	UBYTE			UR_MENUSET
	UBYTE			UR_LANGUAGE
	UBYTE			UR_CALLSTODAY
	UBYTE			UR_GENDER
	LABEL			UR_SIZE

*
* Bit definitions for the UR_FLAGS field
*

	BITDEF		uf,More,0
	BITDEF		uf,Expert,1
	BITDEF		uf,HotKeys,2
	BITDEF		uf,No8Bit,3
	BITDEF		uf,Validated,4
	BITDEF		uf,ClrScr,5
	BITDEF		uf,LogUser,6
	BITDEF		uf,NoANSI,7
	BITDEF		uf,CRLF,8
	BITDEF      uf,Valid,9
   BITDEF      UF,WANTRIP,10
   BITDEF      UF,DELETED,11
   BITDEF		UF,AMIGAANSI,12

*
* Defines for the UR_GENDER field
*

GEN_UNKNOWN		EQU		0
GEN_MALE			EQU		1
GEN_FEMALE		EQU		2

*
* User Index
*

	STRUCTURE	UIDX,0
	STRUCT		ui_Name,40
	STRUCT		ui_Alias,40
   ULONG			ui_DataPos
	LABEL			ui_SIZE

KEY_ALPHAFORWARD		EQU	1
KEY_ALPHAREVERSE		EQU	2
KEY_CHRONOFORWARD		EQU	3
KEY_CHRONOREVERSE		EQU	4

	STRUCTURE	UKEY,0
	APTR			uk_Current
	LONG			uk_Offset
	UWORD			uk_Direction
	LABEL			uk_SIZE

*
* The device config structure
*

	STUCTURE		DC,0
	STRUCT		DC_DEVICE,40
	ULONG			DC_UNIT
	ULONG			DC_DEVBUFFSIZE
	ULONG			DC_BAUD
	ULONG			DC_EXTFLAGS
	ULONG			DC_BRKTIME
	ULONG			DC_SERFLAGS
	ULONG			DC_FLAGS
	UBYTE			DC_CHARLEN
	UBYTE			DC_STOPBITS
	LONG			DC_USEDSR
	STRUCT		DC_RING,40
	STRUCT		DC_NOCON,40
	STRUCT		DC_CON,40
	STRUCT		DC_ANSWER,40
	STRUCT		DC_HANGUP,40
	STRUCT		DC_INIT,40
	LABEL			DC_SIZE

*
* Flags for the DC_FLAGS field
*
	BITDEF		DC,OPENDEV,0
	BITDEF		DC,SCRIPT,1

*
* The line structure
*

	STRUCTURE	LE,0
	STRUCT		LE_USER,UR_SIZE
	STRUCT		LE_DEVCFG,DC_SIZE
	ULONG			LE_NUMBER
	ULONG			LE_REALBAUD
	BOOL			LE_CARRIER
	LABEL			LE_SIZE

	ENDC	; LIBRARIES_PIPELINE_I
