Ambos.font
8
c:smartplay
nw
stopp




------------------------------------------------------------------------
Erklärung:
----------

1. Zeile = Fontsatz für das Ruffenster und das Eilinfofenster.
2. Zeile = Fontsatzgröße
3. Zeile = Pfad des Moduleplayers (auch Name natürlich;-)) )
4. Zeile = Startparameter für den Modulplayer (eventueller)
5. Zeile = Stopp-Parameter für den Modukplayer, sonst geht die Mukke
           nicht mehr aus !:-)
6. Zeile = Ein 'W' damit sich das Eilinfofenster auf der WB öffnet,
           ansonsten öffnet es einfach auf dem obersten Screen.
           (Natürlich wird bei 'W' die Workbench auch nach vorne
            gezogen:-) )


PS: Bei irgendeinemn späteren Update werd ich dafür nochmal einen
    extra Configeditor basteln, aber so gehts ja auch erstmal!

