 Honcho           *UPLOADED* to section 25 stacy02.lha      On Fri Dec 11, 1992 05:03 PM
 Honcho           *UPLOADED* to section 25 stacy03.lha      On Fri Dec 11, 1992 05:03 PM
 The Kid          *UPLOADED* to section 05 showiz           On Sun Dec 13, 1992 04:37 AM
 Shadow Zone      took from section     16 probbs.lha       On Mon Dec 14, 1992 02:39 PM
 Shadow Zone      took from section     16 probbs.lha       On Mon Dec 14, 1992 02:39 PM
 Shadow Zone      took from section     16 protobbs.lzh     On Mon Dec 14, 1992 02:40 PM
 Shadow Zone      took from section     16 protobbs.lzh     On Mon Dec 14, 1992 02:40 PM
 Shadow Zone      took from section     16 protobbs.lzh     On Mon Dec 14, 1992 02:54 PM
 Shadow Zone      took from section     16 protobbs.lzh     On Mon Dec 14, 1992 02:55 PM
 Shadow Zone      *UPLOADED* to section 03 xprbimodem101.lh On Mon Dec 14, 1992 03:00 PM
 Black Sabbath    took from section     10 4DBeta.lha       On Tue Dec 15, 1992 06:18 AM
 Black Sabbath    *UPLOADED* to section 06 startup.lha      On Tue Dec 15, 1992 06:20 AM
 Black Sabbath    took from section     10 4DBeta.lha       On Tue Dec 15, 1992 10:06 AM
 Black Sabbath    took from section     10 4DBeta.lha       On Tue Dec 15, 1992 02:58 PM
 Powersurge       took from section     10 4DBeta.lha       On Tue Dec 15, 1992 07:43 PM
 Powersurge       *UPLOADED* to section 06 ren&stimpyicon.l On Tue Dec 15, 1992 07:45 PM
 Powersurge       took from section     10 4DBeta.lha       On Tue Dec 15, 1992 07:45 PM
 Powersurge       took from section     10 4DBeta.lha       On Tue Dec 15, 1992 08:02 PM
 Powersurge       took from section     10 4DBeta.lha       On Tue Dec 15, 1992 08:08 PM
 Powersurge       took from section     10 4DBeta.lha       On Wed Dec 16, 1992 11:04 AM
 Powersurge       took from section     10 4DBeta.lha       On Wed Dec 16, 1992 11:04 AM
 Powersurge       took from section     10 4DBeta.lha       On Wed Dec 16, 1992 11:08 AM
 Black Sabbath    took from section     10 4dbeta.lha       On Wed Dec 16, 1992 12:08 PM
 Black Sabbath    took from section     10 editors.lha      On Wed Dec 16, 1992 12:09 PM
 Powersurge       took from section     01 4D-List.lha      On Wed Dec 16, 1992 10:50 PM
 Black Sabbath    took from section     10 4DBeta.lha       On Thu Dec 17, 1992 12:28 PM
 Black Sabbath    took from section     10 menus.lha        On Thu Dec 17, 1992 12:28 PM
 Black Sabbath    took from section     10 menus.lha        On Thu Dec 17, 1992 12:37 PM
 Black Sabbath    took from section     10 4DBeta.lha       On Thu Dec 17, 1992 12:37 PM
 Black Sabbath    took from section     10 menus.lha        On Thu Dec 17, 1992 12:37 PM
 Black Sabbath    took from section     10 4DBeta.lha       On Thu Dec 17, 1992 12:37 PM
 Black Sabbath    took from section     10 menus.lha        On Thu Dec 17, 1992 12:38 PM
 Black Sabbath    took from section     10 4DBeta.lha       On Thu Dec 17, 1992 12:38 PM
 Black Sabbath    took from section     10 menus.lha        On Thu Dec 17, 1992 12:38 PM
 Black Sabbath    took from section     10 4DBeta.lha       On Thu Dec 17, 1992 12:38 PM
 Black Sabbath    took from section     10 menus.lha        On Thu Dec 17, 1992 12:39 PM
 Black Sabbath    took from section     10 4DBeta.lha       On Thu Dec 17, 1992 12:39 PM
 Black Sabbath    took from section     10 4dbeta.lha       On Thu Dec 17, 1992 01:11 PM
 Black Sabbath    took from section     10 menus.lha        On Thu Dec 17, 1992 01:12 PM
 Corey Hubbard    took from section     02 blonde.iff       On Fri Dec 18, 1992 02:42 AM
 Corey Hubbard    took from section     02 blonde.iff       On Fri Dec 18, 1992 02:47 AM
 Roentgen         *UPLOADED* to section 21 sc6_1.lha        On Fri Dec 18, 1992 10:37 AM
 Roentgen         *UPLOADED* to section 21 Indent.lha       On Fri Dec 18, 1992 10:48 AM
 Black Sabbath    took from section     10 menus.lha        On Fri Dec 18, 1992 12:46 PM
 Black Sabbath    took from section     01 ShowUser.Lha     On Fri Dec 18, 1992 12:55 PM
 Black Sabbath    took from section     01 FileEd.Lha       On Fri Dec 18, 1992 12:55 PM
 Black Sabbath    took from section     01 BullEd.Lha       On Fri Dec 18, 1992 12:55 PM
 Black Sabbath    took from section     01 4d_stats124.lzh  On Fri Dec 18, 1992 12:55 PM
 Roentgen         *UPLOADED* to section 19 makelibrary.lha  On Fri Dec 18, 1992 01:45 PM
 Black Sabbath    took from section     10 4dbetadat.lha    On Fri Dec 18, 1992 09:11 PM
 Roentgen         *UPLOADED* to section 11 rexxview.lha     On Sat Dec 19, 1992 11:44 AM
 Black Sabbath    took from section     08 andro.lzh        On Sat Dec 19, 1992 08:14 PM
 Black Sabbath    took from section     08 andro.lzh        On Sat Dec 19, 1992 08:16 PM
 Black Sabbath    took from section     08 andro.lzh        On Sat Dec 19, 1992 08:17 PM
 Black Sabbath    took from section     08 andro.lzh        On Sat Dec 19, 1992 08:19 PM
 Corey Hubbard    took from section     25 stacy03.lha      On Sat Dec 19, 1992 09:19 PM
 Corey Hubbard    took from section     25 stacy02.lha      On Sat Dec 19, 1992 09:19 PM
 Shadow Zone      took from section     01 4dbbsx.lzh       On Sat Dec 19, 1992 09:34 PM
 The Care Taker   took from section     21 Spright_V1_2.lzh On Sat Dec 19, 1992 11:05 PM
 The Care Taker   took from section     21 Indent.lha       On Sat Dec 19, 1992 11:07 PM
 The Care Taker   took from section     21 Indent.lha       On Sat Dec 19, 1992 11:07 PM
 Corey Hubbard    took from section     09 akit29b.lha      On Sun Dec 20, 1992 12:43 AM
 Matt             took from section     11 ARTUT.LZH        On Sun Dec 20, 1992 03:31 AM
 Matt             took from section     11 RHost_12.LhA     On Sun Dec 20, 1992 03:31 AM
 Matt             took from section     11 rexxhostlib.36.1 On Sun Dec 20, 1992 03:31 AM
 Matt             took from section     11 Exxec.lha        On Sun Dec 20, 1992 03:31 AM
 Matt             took from section     11 SimpleRexx.lha   On Sun Dec 20, 1992 03:31 AM
 Arcade           *UPLOADED* to section 13 fastcash.zip     On Sun Dec 20, 1992 04:21 PM
 Corey Hubbard    took from section     13 fastcash.zip     On Sun Dec 20, 1992 08:16 PM
 Corey Hubbard    took from section     13 fastcash.zip     On Mon Dec 21, 1992 09:16 PM
 Dr. Darklord     took from section     25 stacy03.lha      On Mon Dec 21, 1992 10:19 PM
 Dr. Darklord     took from section     25 stacy02.lha      On Mon Dec 21, 1992 10:19 PM
 Roentgen         *UPLOADED* to section 02 vtek103.lha      On Wed Dec 23, 1992 07:33 PM
 Roentgen         *UPLOADED* to section 21 perl.lzh         On Wed Dec 23, 1992 09:30 PM
 Corey Hubbard    took from section     02 vtek103.lha      On Thu Dec 24, 1992 04:00 AM
 Black Sabbath    took from section     10 4dbeta.lha       On Thu Dec 24, 1992 01:09 PM
 Black Sabbath    took from section     10 4dbeta.lha       On Thu Dec 24, 1992 01:10 PM
 Black Sabbath    took from section     10 4dbeta.lha       On Thu Dec 24, 1992 01:11 PM
 Roentgen         took from section     01 4d164d.lha       On Thu Dec 24, 1992 01:20 PM
 Powersurge       took from section     10 menus.lha        On Thu Dec 24, 1992 11:05 PM
 Jinx             took from section     10 4dbetadat.lha    On Fri Dec 25, 1992 07:28 AM
 Jinx             took from section     01 def_say.dat      On Fri Dec 25, 1992 07:30 AM
 Jinx             took from section     01 def_say.dat      On Fri Dec 25, 1992 07:31 AM
 Roentgen         *UPLOADED* to section 08 BBSChess.LhA     On Fri Dec 25, 1992 08:21 AM
 Roentgen         *UPLOADED* to section 21 sas_unix.lha     On Fri Dec 25, 1992 08:37 AM
 Challe           took from section     10 4DBeta.lha       On Fri Dec 25, 1992 09:55 AM
 Challe           took from section     10 editors.lha      On Fri Dec 25, 1992 09:57 AM
