    Welcome to the ^nodetitle  Thank you for calling.  A few things
 before you create your account.^n
 1.  You MAY use an ALIAS for your name, if you do not like your^s
current Alias, then leave mail to the sysop and he will change^s
it for you.^n
 2.  Choose a password that is different from any other passwords^s
you use.  DON'T use your USERNAME as your password, because^s
it is EXTREMELY easy to guess and the BBS will not allow it anyway!^n
 3.  There are no TIME LIMITS at all.  The only requirment is you^s
don't hog the system.  There are also no DOWNLOAD LIMITS either,^s
but don't abuse the privileges.  They can be revoked.  We welcome^s
Amiga, IBM, and MAC files, but this is primarily an Amiga BBS.^n
 4. We have door games.  You can find them in their rooms, do a^s
;k to see the rooms.  Doors can be used from any room, the^s
rooms that are of the same name are for messages you wish to^s
post concerning those dirty dealings and things.  Oh, btw, the^s
door rooms are anonymous so you can sign your door names to your^s
posts for a little more fun.  Do a "D" to see the ones available^s
in the current room.
