%CLS.%BC=0.

%BC=7.%TC=4. File Controller >> %BC=0.%TC=7.

You are now within the file-conference controller. From here your
commands are most powerful and for this matter documentation will
be provided here within the next day or so.

Whenever you feel that you are wish to understand a option with more
depth or are not quite sure about some options within your current
conference you will generally find a help key.

<Help on this section to come [Sorry for the Delay]>

%TC=1.ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ%TC=3. Key Press%TC=1. >>%TC=7.%WAITKEY.
