
%BC=7.%TC=4. Begin Index Position: %BC=0.%TC=7.

The options here allow you to start displaying from one end of a index.

%BC=4.%TC=7. Forward Scan: %BC=0.%TC=7.

This starts display from the 'default' (top) of the index. If you had
sorted the index Alphabetically then this would start the displaying
of files from A-Z.

%BC=4.%TC=7. Reverse Scan: %BC=0.%TC=7.

This starts display from the Bottom of the index. If you had
sorted the index Alphabetically then this would start the displaying
of files from Z-A.

%TC=5.End of Help [Return to Continue] %TC=6.=>%TC=7. %WAITKEY.Continue

