

%BC=4.%TC=7. Sorting Information >> %BC=0.%TC=7.

Within the command menu you have options of changing the way the index
is presented to you.

%BC=7.%TC=4. Natural Sorting: %BC=0.%TC=7.

Normally the index is displayed in 'Natural' order (default) which is
basically the contents of the file index "as is" which will contain files
in 'any old order' and requires no sorting at all as you are using just
the default display.

%BC=7.%TC=4. Sorting via Size: %BC=0.%TC=7.

This will sort the index according to the 'size' of the files within
the index. You will then be able to display the sorted area according
to either the 'largest size to lower size' or 'lowest size to largest
size', this is quite a good idea in finding 'quality' files which
tend to be rather large and sometimes hard to locate. Seperating
large files from shorter files has a lot of advantages.

%BC=7.%TC=4. Sorting via Date: %BC=0.%TC=7.

This sorts the files according to their Chronological dates. Once this
has been done you are then able to display the index from the 'last
added files to the first added files' or the other way round. This
option is very handy if you wish to seperate the newest files from
the older files.

%BC=7.%TC=4. Sort Alphabetically: %BC=0.%TC=7.

This does much as it says , the files are sorted according to the
A-Z format, and then you are able to list from either Z to A or A to Z.
Once again, this option is very handy if you know the first letter of
a file and wish to try and locate it.

%TC=5.End of Help [Press return to Continue] %TC=6.=> %TC=7.%WAITKEY.Continue...
