     converse "Command" "CHAT N\n" 
     converse "Command" "U A\n\n"
     converse "postal code" "^x\wUsing ARM ScRiPt!\n\n\n" 
     converse "Command" "U L 0 T Z M Y Y Y Y Y N AF J\n"
     when "New name" send "\n"
     when "Format Choice" send "A\n"
     when "not available" send "AF A\n"
     converse "Command" "U S IBM\n"
     converse "Command" "X Super\n"
     dlwhen
     dlwhen
     dlwhen
     converse "Command" "GRAB\n"
     timeout 0

