;    Erkka Samsten = Arm MBBS script fixer to BBBS!  
;     -*-*-*- Scripts v1.1 - Last update: 16.12.92 -*-*-*-
;      Hope you enjoy Using Fixed MBBS scripts.;->
;        BTW: You can (and you must) spread this in other BBBSes!
;         I Don't want a huge phonebill..you spread!-)

     set $charset = "IBM"
     request off
     timeout 10 gosub TryAgain
     when "--more--" send "c"
     when "SYSOP is coming online" gosub ShutUp
     when "Include original message" send "N\n"
     when "not available for reply" send "COM\n"
     when "Invalid conference selection" send "COM\n"
     when "Send carbon copies" send "N\n"
     when "Daily time limit" quit

     timeout 60 gosub TryAgain
     converse "FIRST name" "%USERNAME\n"
