     converse "Command" "F GET\n"
     timeout 0
     wait "Command"
     cli "delete > NIL: \"%GRABPATH.newfiles\""
     capture "%GRABPATH.newfiles"
     timeout 1800 gosub TryAgain
     send "F N\n"
     converse "Date to scan" "\n"
     wait "Command"
     capture off
     send "^x"
     converse "Command" "U A\n\n"
     converse "postal code" "^x\w23100 Mynämäki\n\n\n" ; Change that!
     converse "Command" "X Junior\n"
     converse "Command" "U L 24\n"
     timeout 60 gosub TryAgain

LogOut:
     Send "G Y\n"
     dwhens

