     converse "Command" "F PU\n"
     converse "upload for" "%RECEIVER\n"
     converse "File name" "%FILENAME\n"
     converse "description" "%DESC\n"
     wait "B01"
     upload "%FILEPATH",Z
     timeout 0
     converse "Enter detailed" "Y\n"
     wait "+----7-"
     ascsend "%GRABDIR%FILENAME.fileinfo"
     cli "delete %GRABDIR%FILENAME.fileinfo"
     send "^z"
     wait "Command"
     send "\w^x"

