     wait "\r\nNO CARRIER\r\n"
     cli "execute >NIL: \"%GRABPATH.exe\""
     message "\n ..> End of ScRiPt <..\n"
     request on
     end

ShutUp:
     beep
     send "\n  !!..> You are ChAtTiNg with of ScRiPt file <..!!\n"
     send "          SaY something.. I'm maybe OnLiNe\n\n\n"
     timeout 0
     wait "SYSOP is going offline"
     timeout 60 gosub TryAgain
     return

TryAgain:
     send "^x"
     timeout 60 goto Quit
     return

Quit:   message "\n !!..> The board has hung...Call the SysOp(s) <..!!\n"
     beep
     end
