;
; FAX_Answer.script
; =================
;
; Diese Script startet MultiFax von TKR wenn die externe Faxweiche
; auf Fax erkannt hat. Sie benötigen diese Script nicht wenn Ihr Modem eine
; automatischen Faxerkennung hat. In diesem Fall wird das Fax_Receive.script
; gestartet wobei dann keine externe Faxweiche notwendig ist.
;
; Weiters benötigt MultiFax im Rexx Verzeichnis die Datei Answer.mfx welche
; Sie im Utilities Verzeichnis Ihrer GMC-BBS Disk finden. Kopieren Sie diese
; Datei bitte händisch in das entsprechende Verzeichnis !
;

SYS:Rexxc/RX MultiFax:Rexx/Answer.mfx
