;
; FAX_Receive.script
; ==================
;
; Diese Script startet MultiFax von TKR wenn das Modem auf
; Fax erkannt hat. Sie benötigen diese Script nicht wenn Ihr Modem keine
; automatische Faxerkennung hat. In diesem Fall wird das Fax_Answer.script
; gestartet wobei dann eine externe Faxweiche notwendig ist.
;
; Weiters benötigt MultiFax im Rexx Verzeichnis die Datei Receive.mfx welche
; Sie im Utilities Verzeichnis Ihrer GMC-BBS Disk Finden. Kopieren Sie diese
; Datei bitte händisch in das entsprechende Verzeichnis !
;

SYS:Rexxc/RX MultiFax:Rexx/Receive.mfx
