

;;; If you have trouble receiving faxes after data calls , then use
;;; this script to initialize your faxmodem.
;;; run it after each data call.
;;; In the logout , incoming and callhub scripts.

trion:utils/trion -1 -P0                       ;trion serial port off

failat 21

wait 1
rx "address rexx_gpfax openserial"
wait 1
rx "address rexx_gpfax initmodem"
wait 3
rx "address rexx_gpfax closeserial"
wait 1

failat 10

trion:utils/trion -1 -P1                       ;trion serial port on



