#
#	$Id: inetd.conf,v 4.4 1994/10/05 00:28:04 jraja Exp $
#
#	The inetd configuration file.
#
#	Copyright © 1994 AmiTCP/IP Group,
#	                 Network Solutions Development Inc.
#	                 All rights reserved.
#
# Inetd reads its configuration information from this file upon
# execution and at some later time if this file is changed or inetd 
# is reconfigured in response with a CTRL-F signal.
#
##
#
# Configuration lines are parsed with DOS function ReadItem().
# Multiple line entries must have a ``+'' char as the last char in the
# line. First 6 fields must be present in each entry. The line has
# following entries in this order:
#
# service socket-type protocol wait user server cli-name cli-arguments
#
##
#       inetd internal services
##
# 
#±{EnableMail}smtp      stream      tcp nowait root AmiTCP:serv/SMTPServer
#±{EnableMail}pop3      stream      tcp nowait root AmiTCP:serv/POP3Server
#±{EnableIRC}clchat    stream      tcp nowait root AmiTCP:serv/clchatd
#±{EnableIRC}clchatirc stream      tcp nowait root AmiTCP:serv/clchatircd
#±{EnableFTP}ftp       stream      tcp nowait root AmiTCP:serv/ftpd in.ftpd
daytime   stream      tcp nowait root internal
daytime   dgram       udp nowait root internal
time      stream      tcp nowait root internal
time      dgram       udp nowait root internal
echo      stream      tcp nowait root internal
echo      dgram       udp nowait root internal
discard   stream      tcp nowait root internal
discard   dgram       udp nowait root internal
chargen   stream      tcp nowait root internal
chargen   dgram       udp nowait root internal
# An experimental finger server
finger    stream tcp nowait nobody amitcp:serv/in.fingerd -in.fingerd s:.plan
# NetFS, a networking support between Amigas
# Remove # from the next line to enable NetFS
#amiganetfs stream    tcp nowait root amitcp:serv/netfs-server
#
# net/2 ftp daemon ported by Magnus Lilja
#
#ftp       stream      tcp nowait root AmiTCP:serv/ftpd ftpd -l -x
#
# Naive servers
whois     stream tcp dos bin - echo The whois service is not installed
telnet    stream tcp dos bin - echo The telnet service is not installed
quote     stream tcp dos bin - +
echo "Ei tästä pidot parane, ellei vierahat vähene."
###
## Emacs magic:
## Local Variables: **
## backup-by-copying:t **
## End: **
###
