                ______
 SUPPORTING    /  /  /   SUPPORT YOUR COMPUTER.  IF YOU USE IT, BUY IT
              /  /  /
 CNet Amiga  /  /  /          This File Originated From Ami West!
   WB 2.1   /  /  /
  ______   /  /  /               A M I G A - I B M - A M I G A
  \  \  \ /  /  /
   \  \  /  /  /     Line #1 (707)/445-8277    Line #2 (707)/442-6648 {HST}
    \  \/  /  /
     \____/__/          U.S. Robotics HST/V42bis - GVP 68030/25 385 Megs

 SysOp : Dragon Slayer   -=-   SAN/ADS HUB SITE   -=-   FidoNet: (1:125/38.0)

 Magic Name For File List Request :

 FILES    -> Updated sorted list of files (LHA format).

------------------------------------------------------------
Please add your BBS name to the list and pass this along....
------------------------------------------------------------

  BBS Name              Phone Number    Baud   Address       Sysop
-------------------------------------------------------------------------------
1 Ami West (Line 2)     1-707-442-6648  HST    1:125/38.0    Mike Steele
2 Ami West (Line 1)     1-707-445-8277  2400   <NONE>        Mike Steele
3
4
5
6
7
8
9
10

---------------------------------------
Official CNet Amiga Beta Test Site!!!!
---------------------------------------

This BBS List Foo is always for you!!!!



