
BOOL __asm __saveds HBBS_InitCommon( void );
void __asm __saveds HBBS_CleanUpCommon( void );
ULONG __asm __saveds SafePutToPort(register __a0 struct Message *message, register __a1 STRPTR portname);
struct Message __asm __saveds *SendMessage(register __a0 struct Message *Msg,register __a1 char *MPortName);
V_BIGNUM __asm __saveds HBBS_Reserved_1( register __a0 struct List *list);
void __asm __saveds FreeStrList(register __a0 V_STRINGLIST strlist);
struct BBSGlobalData __asm __saveds *HBBS_GimmeBBS( void ) ;
void __asm __saveds HBBS_SetBBS(register __a0 struct BBSGlobalData *B);
struct Node __asm __saveds *GetNode(register __a0 struct List *lh,register __d0 UWORD n);
UWORD __asm __saveds GetNodeNum(register __a0 struct List *lh,register __a1 struct Node *node);
struct NodeData __asm __saveds *HBBS_NodeDataPtr(register __d0 short nodenum);
V_ERROR __asm __saveds HBBS_LogError(register __a0 V_STRING filename,register __d0 V_ERROR errnum,register __a1 V_STRING string,register __d1 V_ERROR errtype);
struct CfgFileData __asm __saveds *HBBS_LoadConfig(register __a0 UBYTE *filename,register __d0 ULONG Flags);
void __asm __saveds HBBS_FlushConfig(register __a0 struct CfgFileData *cfgfile);
V_BOOL __asm __saveds HBBS_SaveConfig(register __a0 struct CfgFileData *cfgfile);
struct CfgItemData __asm __saveds *HBBS_GetCfgNode(register __a0 struct CfgFileData *cfgfile,register __a1 V_STRING optionstr);
V_SMALLNUM __asm __saveds HBBS_GetSetting(register __a0 struct CfgFileData *cfgfile,register __a1 void **result,register __d0 V_FLAGS optiontype,register __a2 V_STRING optionstr,register __d1 V_BOOL multi);
struct CfgFileData __asm __saveds *HBBS_CreateConfig(register __a0 UBYTE *filename);
BOOL __asm __saveds HBBS_RemoveCfgItem(register __a0 struct CfgFileData *cfgfile,register __a1 UBYTE *itemname);
V_BOOL __asm __saveds HBBS_AddCfgItem(register __a0 struct CfgFileData *cfgfile,register __a1 UBYTE *itemname,register __a2 UBYTE *params);
void __asm __saveds HBBS_ResetNodeData(register __a0 struct NodeData *node);
void __asm __saveds HBBS_rterror(register __a0 char *str);
LONG __asm __saveds HBBS_RunDOSCMD(register __a0 char *command,register __d0 BOOL ASYNC);
void __asm __saveds HBBS_DoErrorMessage(register __d0 ULONG num,register __d1 ULONG node,register __a0 char *errstr);
void __asm __saveds FreeStr(register __a0 char *str);
char *__asm __saveds DupStr(register __a0 char *str);
char *__asm __saveds FreeAndSet(register __a0 char **varname,register __a1 char *newstr);
V_BOOL __asm __saveds CheckBoolean(register __a0 char *str);
V_ERROR __asm __saveds NewStrNode(register __a0 char *str,register __a1 struct List *list);
void __asm __saveds UpperCase(register __a0 char *str);
char *__asm __saveds upcase(register __a0 char *str);
short __asm __saveds position(register __a0 char *substr,register __a1 char *str);
short __asm __saveds iposition(register __a0 char *substr,register __a1 char *str);
void __asm __saveds strfcpy(register __a0 char *dest,register __a1 char *source,register __d0 int from);
void __asm __saveds stripcr(register __a0 char *s);
void __asm __saveds StripComments(register __a0 char *s);
void __asm __saveds StripSpaces(register __a0 char *s);
void __asm __saveds replace(register __a0 char *dest,register __a1 char *compare,register __a2 char *from,register __a3 char *to);
BOOL __asm __saveds GetParams(register __a0 char *dest,register __a1 char *source);
BOOL __asm __saveds GetItem(register __a0 char *dest,register __a1 char *source);
void __asm __saveds GetNumber(register __a0 int *num,register __a1 char *item);
void __asm __saveds HBBS_Reserved_2(register __a0  char *str);
BOOL __asm __saveds AssignOK(register __a0 char *checkme );
struct TimerData __asm __saveds *SubmitTimer(register __a0 struct TimerSetupData *TSD, register __d0 ULONG Seconds,register __d1 ULONG MicroSeconds );
void __asm __saveds AbortTimer(register __a0 struct TimerSetupData *TSD, register __a1 struct TimerData *CTD);
BOOL __asm __saveds CheckTimer(register __a0 struct TimerSetupData *TSD, register __a1 struct TimerData *CTD);
void __asm __saveds CleanupTimer( register __a0 struct TimerSetupData *TSD );
struct TimerSetupData __asm __saveds *InitTimer( void );
BOOL __asm __saveds PathOK(register __a0 char *str);
V_BOOL __asm __saveds  HBBS_LoadUser(register __d0 V_BIGNUM fileoffset,
                                     register __d1 V_BIGNUM ID,
                                     register __a0 char *handle,
                                     register __a1 char *realname,
                                     register __a2 struct UserData *User,
                                     register __d2 ULONG Flags);
V_BOOL __asm __saveds HBBS_ValidUserHandle(register __a0 char *userhandle, register __a1 struct UserData *FillUser);
V_BIGNUM __asm __saveds HBBS_FindTotalUsers( void );
BOOL __asm __saveds LoadPrivateData( void );
void __asm __saveds UpdatePrivateData ( void );
BOOL __asm __saveds HBBS_AddUser(register __a0 struct UserData *user);
void __asm __saveds HBBS_InitUserData(register __a0 struct UserData *User,register __d0 V_BIGNUM AccessLevel,register __d1 V_BIGNUM ConfNum);
void __asm __saveds strNcpy(register __a0 UBYTE *dest,register __a1 UBYTE *source,register __d0 int chars);
char *__asm __saveds HBBS_ListName(register __a0 V_STRINGLIST ListName,register __d0 V_SMALLNUM ItemNum);
void __asm __saveds FreeFileTags( register __a0 struct NodeData *N_ND );
struct List __asm __saveds *HBBS_LoadFile(register __a0 char *filename);
BOOL __asm __saveds HBBS_SaveFile( register __a0 char *file_name, register __a1 struct List *list);
struct List __asm __saveds *HBBS_CreateList( void );
void __asm __saveds RemoveSpaces(register __a0 char *string);
void __asm __saveds strftcpy(register __a0 char *dest,register __a1 char *source,register __d0 int from,register __d1 int topos);
void __asm __saveds HBBS_SaveUserData(register __a0 struct UserData *User);
char __asm __saveds *HBBS_GetDate(register __a0 char *datestr);
V_BOOL __asm __saveds HBBS_AddCfgItemQuick(register __a0 struct CfgFileData *cfgfile,register __a1 char *ItemName, register __a2 char *Params);
void __asm __saveds HBBS_SaveCallsData( void );
void __asm __saveds HBBS_LoadCallsData( void );
char  __asm __saveds *HBBS_GetTime(register __a0 char *timestr);
char __asm __saveds *HBBS_GetDateString(register __a0 char *datestr,register __d0 ULONG AmigaTime);
V_BOOL __asm __saveds HBBS_CopyFile(register __a0 char *fromfile, register __a1 char *tofile,register __d0 ULONG BufSize);
ULONG __asm __saveds HBBS_NodesInList(register __a0 struct List *list);
V_BOOL __asm __saveds HBBS_AppendStrToFile(register __a0 UBYTE *FileName, register __a1 UBYTE *String);
struct Node __asm __saveds *HBBS_CreateNode(register __a0 char *namestr,register __d0 ULONG nodesize);
void __asm __saveds HBBS_FreeNode(register __a0 struct Node *node,register __d0 V_BOOL RemoveIt);
void __asm __saveds HBBS_FreeListNodes(register __a0 struct List *list);
V_BOOL __asm __saveds HBBS_SendOLM(register __d0 V_SMALLNUM FromNode,register __a0 UBYTE *FromPRG,register __d1 V_SMALLNUM ToNode,register __a1 UBYTE *MessageStr,register __d2 BYTE Pri);
BOOL __asm __saveds FGetsR(register __a0 BPTR FH,register __a1 UBYTE *Buffer,register __d0 LONG BufferLen);
struct Node __asm __saveds *HBBS_FindNode(register __a0 struct List *list,register __a1 char *str);
V_BIGNUM __asm __saveds HBBS_FindNodeNum(register __a0 struct List *list, register __a1 char *str);
V_BOOL __asm __saveds HBBS_HandleNameOK(register __a0 char *checkstr);
int __asm __saveds strNIcmp(register __a0 char *s1, register __a1 char *s2,register __d0 const int n);
V_BIGNUM __asm __saveds HBBS_GetFileSize(register __a0 char *filename);
V_BOOL __asm __saveds HBBS_FindConfFile(register __d0 V_BIGNUM ConfNum,register __a0 char *filename,register __a1 char *fullname);
char __asm __saveds *HBBS_GetTimeDateString( register __d0 ULONG AmigaTime );
ULONG __asm __saveds HBBS_GetAmigaTime( void );
ULONG __asm __saveds HBBS_DateStrToAmigaTime(register __a0 char *datestr);
struct CfgFileData __asm __saveds *HBBS_LoadConfigQuick(register __a0 UBYTE *filename,register __d0 ULONG Flags,register __a1 UBYTE *PatternStr);
BPTR __asm __saveds HBBS_LockUserData( register __d0 ULONG LockMode );
void __asm __saveds HBBS_UnLockUserData( void );
V_BOOL __asm __saveds HBBS_HandleInUse(register __a0 char *userhandle, register __d0 CurrentID, register __a1 struct UserData *FillUser);
char __asm __saveds *HBBS_AccessName(register __d0 V_SMALLNUM Access);
void __asm __saveds HBBS_ApplyAccountDefaults( register __a0 struct UserData *User );
LONG __asm __saveds HBBS_DosCommand(register __a0 char *command,register __d0 ULONG Flags,register __a1 char *outputfilename);
ULONG __asm __saveds HBBS_OkToUpload(register __a0 char *filename);
void __asm __saveds HBBS_ClearCommentsFromList(register __a0 struct List *list);
struct List __asm __saveds *HBBS_LoadKey( void );
BOOL __asm __saveds HBBS_AddCfgList(register __a0 struct CfgFileData *cfgfile,register __a1 struct List *list,register __a2 char *itemname);
char __asm __saveds *HBBS_GetWeekStartDate(register __a0 char *datestr, register __d0 ULONG AmigaTime);
