
%TC=7.Please select one of the computer formats from this list that pertains
to the computer section that you are using or are interested within.

%BOLD=1.%TC=1.Computer types:

%TC=2.1  %TC=5.- %TC=3.%-17.17s %TC=2.2  %TC=5.- %TC=3.%-17.17s %TC=2.3  %TC=5.- %TC=3.%-17.17s 
%TC=2.4  %TC=5.- %TC=3.%-17.17s %TC=2.5  %TC=5.- %TC=3.%-17.17s %TC=2.6  %TC=5.- %TC=3.%-17.17s
%TC=2.7  %TC=5.- %TC=3.%-17.17s %TC=2.8  %TC=5.- %TC=3.%-17.17s %TC=2.9  %TC=5.- %TC=3.%-17.17s 
%TC=2.10 %TC=5.- %TC=3.%-17.17s %TC=2.11 %TC=5.- %TC=3.%-17.17s

%BOLD=0.%TC=5.Computer Type %TC=6.=>%TC=7.