%TC=7.
======================================

Your Name        --> %BOLD=1.%TC=1.%s%BOLD=0.%TC=7.
Your Password    --> %BOLD=1.%TC=1.%s%BOLD=0.%TC=7.

======================================

Make a note of these!  You will need them to signon to the system again.

%TC=1.ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ%TC=3. Press a key%TC=1. >>%TC=7.%WAITKEY.

%CURSOR=0.%CLS.
%BOLD=1.%TC=1.IMPORTANT NEW USER INFORMATION:%BOLD=0.%TC=7.

Until your account has been checked by the Sysop your Files access is limited.
This proceedure should only take 24 Hrs maximum.

%BOLD=1.%TC=7.Make quite sure you understand the above.%BOLD=0.%TC=7.

%TC=1.ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ%TC=3. Press a key%TC=1. >>%TC=7.%CURSOR=1.%WAITKEY.
