

To gain full access to this system, it is necessary that you supply your real
name, telephone number, and home address.  These items will under NO
circumstances be made public to anyone, unless you so request.

To receive access to the ApT BBS support areas, you MUST leave your
name, serial number, and place of purchase in feedback.  Access to
these areas is NOT automatic!

You will now be asked to enter several personal data items.  Please respond
truthfully.  All users will be given access to view your Handle and your
City/Country.  You will be asked whether or not to keep the other information
private for System Operators' eyes only.

