
%BOLD=1.%TC=1.Ansi Positioning:%BOLD=0.%TC=7.

Ansi Screen positioning allows your terminal to display text faster and
also enhances the display in most areas. In most cases of terminal
software this option should be turned to ON.

%TC=7.Also, with the use of ANSI cursor movement, you should see the word
"ANSI" spelled out below.

        %CURSOR_RIGHT=4.I%CURSOR_LEFT=2.S%CURSOR_LEFT=2.N%CURSOR_LEFT=2.A

%TC=5.Ansi Screen Positioning [%TC=7.Y/n%TC=5.] %TC=6.=>%TC=7.