
%BOLD=1.%TC=1.Ansi Capability:%BOLD=0.%TC=7.

If your terminal software has "ANSI" ability, you will see the following
text change as indicated:

        This line should look normal.
        %UNDERLINE=1.This line should be underlined.%UNDERLINE=0.
        %BOLD=1.This line should be bold type.%BOLD=0.
        %RVIDEO=1.This line should be reverse video.%RVIDEO=0.

%TC=5.Ansi [%TC=7.Y/n%TC=5.] %TC=6.=>%TC=7.