
%BOLD=1.%TC=2.01%TC=5......%TC=3.Jan     %TC=2.02%TC=5......%TC=3.Feb     %TC=2.03%TC=5......%TC=3.Mar     %TC=2.04%TC=5......%TC=3.Apr     %TC=2.05%TC=5......%TC=3.May
%TC=2.06%TC=5......%TC=3.Jun     %TC=2.07%TC=5......%TC=3.Jul     %TC=2.08%TC=5......%TC=3.Aug     %TC=2.09%TC=5......%TC=3.Sep     %TC=2.10%TC=5......%TC=3.Oct
%TC=2.11%TC=5......%TC=3.Nov     %TC=2.12%TC=5......%TC=3.Dec%BOLD=0.%TC=7.
