;------------------------------------------------------------------------
;                 Oves SommarHus BBS +46-(0)16-146837 
;  $VER: OldCalLog.script 1.1 (29-09-96) Snille Of LoserKlubben.inc
;------------------------------------------------------------------------
;
;Description:  Rename and saves separate CalLogs for every
;              day up to 14 days.
;
;Requirements: CNet 3.05 
;
;Install:      Copy all fles in the archive to PFiles.
;              Don't forget to config OldCalLog.rexx after this.
;              Open Cnets Config module and enter Evets.
;              Add an event as DOS-CMD.
;              write this as Args Execute PFiles:Moore/OldCalLog
;              Time 2400
;              Valid 10
;              Interval 0
;              Iterate 1
;              Select All DAYS
;
;              Add this to your BBSMenu at menu 3; Main prompt:
;              OLC            `30- |#0PFiles:utilities/OldCalLog/OldCalLog.rexx}
;             
;Mail me at:   E-Mail:
;              erik.pettersson@mailbox.swipnet.se
;
;------------------------------------------------------------------------

Failat 50
copy SysData:Log/CalLogs/CalLog14 SysData:Log/CalLogs/CalLog15
copy SysData:Log/CalLogs/CalLog13 SysData:Log/CalLogs/CalLog14
copy SysData:Log/CalLogs/CalLog12 SysData:Log/CalLogs/CalLog13
copy SysData:Log/CalLogs/CalLog11 SysData:Log/CalLogs/CalLog12
copy SysData:Log/CalLogs/CalLog10 SysData:Log/CalLogs/CalLog11
copy SysData:Log/CalLogs/CalLog9 SysData:Log/CalLogs/CalLog10
copy SysData:Log/CalLogs/CalLog8 SysData:Log/CalLogs/CalLog9
copy SysData:Log/CalLogs/CalLog7 SysData:Log/CalLogs/CalLog8
copy SysData:Log/CalLogs/CalLog6 SysData:Log/CalLogs/CalLog7
copy SysData:Log/CalLogs/CalLog5 SysData:Log/CalLogs/CalLog6
copy SysData:Log/CalLogs/CalLog4 SysData:Log/CalLogs/CalLog5
copy SysData:Log/CalLogs/CalLog3 SysData:Log/CalLogs/CalLog4
copy SysData:Log/CalLogs/CalLog2 SysData:Log/CalLogs/CalLog3
copy SysData:Log/CalLogs/CalLog1 SysData:Log/CalLogs/CalLog2
Copy Cnet:sysdata/Log/Calls To SysData:Log/CalLogs/CalLog1
Delete SysData:Log/CalLogs/CalLog15
Delete Cnet:sysdata/Log/Calls
Failat 21
