/*
** Zeus Shortcut Script
**
** ResetStats.zsc
**
**   - This script shuts down Zeus and deletes the statistics
**     and last callers files.
**
** $VER: ResetStats.zsc 1.0 (19.02.96)
** Zeus Bulletin Board System (c)1992-1996 Alex May & Nick Loman
*/

Options Results
Parse Arg Minutes

Address 'ZEUS'

say ''
say 'Zeus Bulletin Board System (c)1992-1996 Alex May & Nick Loman'
say 'Zeus Pointer Reset Script - written by Nick Loman'
say ''

QuitZeus

say 'Waiting for Zeus to close down...'

Call Delay(600)

address command 'Delete Zeus:Config/LastCalls.dat'
address command 'Delete Zeus:Config/Zeus/SystemInfo.dat'

exit
