/* C Headerfile generated by RevUp 1.2 */

#define VERSION		2
#define REVISION	0
#define DATE	"15.10.94"
#define VERS	"LogViewer 2.0"
#define VSTRING	"LogViewer 2.0 (15.10.94)\r\n"
#define VERSTAG	"\0$VER: LogViewer 2.0 (15.10.94)"
