.key comment,path,fn0,fn1,fn2,fn3,fn4,fn5,fn6,fn7,fn8,fn9
if not exists sys:Temp
   makedir sys:Temp
endif
if not exists ram:PF.LHA
   if exists sys:temp/PF3.LHA
      delete sys:temp/PF3.LHA
   endif
   if exists sys:temp/PF2.LHA
      rename sys:temp/PF2.LHA to sys:temp/PF3.LHA
   endif
   if exists sys:temp/PF1.LHA
      rename sys:temp/PF1.LHA to sys:temp/PF2.LHA
   endif
   Failat 21
   lha -P-5 -r -wRAM: -x a ram:PF.LHA <path> <fn0> <fn1> <fn2> <fn3> <fn4> <fn5> <fn6> <fn7> <fn8> <fn9>
   lha a ram:PF.LHA gmc-bbs:bulletins_menu/sys-info.displayme gmc-bbs:bulletins_menu/dl-gmc.displayme
   FileNote ram:PF.LHA "<comment>"
   copy ram:PF.LHA to sys:temp/PF1.LHA clone
   delete ram:PF.LHA
endif
