failat 30

If EXISTS Doors:
  ECHO " "
 Else
  ECHO " "
  ECHO You MUST assign Doors: directory first!
  ECHO " "
  QUIT
EndIf

If NOT EXISTS Doors:mv/
  MAKEDIR Doors:MV
EndIf


If EXISTS Doors:mv/comment/
  ECHO "You already have Doors:mv/Comment directory ?" 
  ECHO " "
  ECHO " It is sugested just to update MV-Comment.CFG file"
  ECHO " (read in DOCS about new statements in config"
  ECHO " "
  Ask  "Do you wish to DELETE [and lose ALL files & configs in it?] (y/N)" 
  If NOT WARN
      ECHO " "
      ECHO "Please, check your config or install door manualy?"
    QUIT
  Else
    ECHO "Are you absolutely sure that you want do DELETE  "
    Ask "all files in Doors:mv/Comment directory ?        (y/N)"
    If WARN
      DELETE doors:mv/Comment/#? ALL QUIET >nil:
    Else
      ECHO " "
      ECHO "Please, check your config or install door manualy?"
      QUIT
   EndIf
  EndIf
Else
  Makedir doors:Mv/Comment >nil:
EndIf

Echo " "
Echo "Copying Mad Virgin COMMENT Door to Doors:MV/Comment/ directory"

COPY comment TO doors:mv/Comment/ ALL CLONE QUIET
If NOT WARN
  ECHO ---------------------------------------------------------------------------
  ECHO "         Mad Virgin Comment door V1.2 for DayDream BBS - AMIGA !"
  ECHO "                                                        (15.05.1997)"
  ECHO " "
  ECHO " INSTALATION OK !"
  ECHO " "
  ECHO " PLEASE READ THE DOCS before install this door on your BBS !!!!"
  ECHO ---------------------------------------------------------------------------
 Else
  ECHO "DAMN! Something is wrong!?"
 EndIf
wait 7
