****
How often do you call Inquestor?
****
once a day             
2-3 times/week         
once a week            
2-3 times a month      
once in a blue moon    
****
Do you call the BBS as often as before ?
****
Yes - MORE often       
Yes - as often         
No  - not as often     
N/A - Fence Sitters!   
****
How do you think the BBS has improved ?
****
Love-it!               
A lot better           
Much The Same          
Who Cares?             
N/A - Fence Sitters!   
****
What feature would be most valued ?
****
Full Screen Editor     
More Message Areas     
Better ANSI            
More Doors             
More Amiga Files       
More IBM Files         
N/A - Fence Sitters!   
*****
What part of the BBS do you use the MOST ?
****
Messages               
Files                  
Doors                  
Textfiles              
N/A - Fence Sitters!   
****
What do you think needs the most work ?
****
Doors                  
Messages               
Files                  
Texts                  
N/A - Fence Sitters!   
****
What's your favourite part of the BBS?
****
Doors                  
Messages               
Files                  
Texts                  
N/A - Fence Sitters!   
****
Do you think the sysop inputs enough into the BBS?
****
Yes                    
No                     
N/A - Fence Sitters!   
****
END
****
