****

R. M. Nixon's the only one for me because he is:
****
Sincere                         
Handsome                        
Ruggedly honest                 
A second-hand car dealer        
Hot on law & order              
American                        
Husband to Pat                  
Daddy to Tricia                 
****
Choose your favourite dish:
****
Rat au Vin                      
Rat a Tue                       
Rat Mure                        
Rats                            
Ratatouille                     
Escargot (really rat)           
****
Choose your fine Australian Wine:
****
Black Stump Bordeaux            
Sydney Syrup                    
Chateau Blue                    
Old Smokey 1968                 
1970 Cotes Rod Laver            
Perth Pink                      
Melbourne Old & Yellow          
Chateau Chunder                 
Hoart Runny                     
Cuve Reserve Nuits Wagga Wagga  
Ainsley Grotto                  
Australian Pommie Juice         
Vieux Rolf Harris               
****
Choose your favourite book:
****
How to Find 5c in the Dark                      
How to Nurse a Sore Toe                         
How to Become Brando's Speech Therapist         
How to Burn a Piece of Paper                    
How to Knock over Sir Zelman Cowan              
How to Measure Greg Norman's inside leg         
****
How do you tell a Boy Scout?
****
by B                            
by C                            
quietly, not to frighten him    
****
In my police career, I'd most like to be involved in:
****
Drugs                           
Putting the boot in             
Naughty people                  
Gambling                        
Cheap holidays                  
Sailors                         
Home knitwear                   
Bribery                         
Obscene books                   
Leisure footwear                
****
Varicose veins can be fun at parties:
****
True                            
False                           
****
If there was an outbreak of rubella at your school you'd worry because:
****
It was German Measles           
It was Chicken Pox              
It was Mumps                    
It was Contagious               
****
At what age should a child be able to make up a simple sentence?
****
18 months                       
14 years                        
37 years                        
****
Julius Caesar was the first:
****
Caesarian birth                 
Roman pouff                     
Doctor                          
****
Your clavicle is:
****
your collar bone                
your harpsichord                
your au pair girl               
****
How many pints does your body contain?
****
between 8 and 10                
between 10 and midnight         
four double gins                
a bottle of whisky              
****
If you burnt your hand cooking, the best thing to do would be:
****
stop cooking                    
eat out                         
put a plaster on it             
get pissed                      
****
A woman's breasts contain:
****
Milk                            
Fun                             
Naughty Secrets                 
****
Nymphomaniacs should be:
****
encouraged                      
put in hospitals                
@#@%$#ed                        
****
Do you really like sex?
****
No                              
Yes                             
What is your address?           
***
END
***
