;Installer script for RIPgraf version 0.80
;
;This script assumes you are installing for the first time!
;

;Ask where to install the program files.

(message
        "Please indicate the directory in which all the RIPgraf files should"
	" be installed. A directory will not be automatically created, therefore"
	" you should create a directory on your own called \"RIPgraf\" or any"
	" name you choose by selecting \"Make New Drawer...\" when asked"
	" which directory to install to."
)

(set name
	(askdir
		(prompt "Which directory should RIPgraf be installed in?")
		(help @askdir-help)
		(default "SYS:")
		(disk)
	)
)

(set @default-dest name)
(set fontdir (cat name "/RIPFONTS"))
(set icondir (cat name "/RIPICONS"))

(makedir fontdir
	(prompt "Creating a directory for storing RIP fonts called\n\n" fontdir)
	(help @makedir-help)
	(infos)
	(confirm)
)
(makedir icondir
	(prompt "Creating a directory for storing RIP icons called\n\n" icondir)
	(help @makedir-help)
	(infos)
	(confirm)
)

(copyfiles
	(prompt "Copying RIP fonts...")
	(help @copyfiles-help)
	(source "ripfonts")
	(dest fontdir)
	(all)
        (confirm)
)

(copyfiles
	(prompt "Copying ICON files...")
	(help @copyfiles-help)
	(source "ripicons")
	(dest icondir)
	(all)
	(confirm)
)

(copyfiles
	(prompt "Copying Amiga fonts...")
	(help @copyfiles-help)
	(source "fonts")
	(dest "FONTS:")
	(all)
        (confirm)
)

(copyfiles
	(prompt "Copying RIPgraf, documentation and support files...")
	(help @copyfiles-help)
	(source "")
	(dest name)
	(choices
		"RIPGRAF"
		"RIPGRAF.info"
		"RIPGRAF.guide"
		"RIPGRAF.guide.info"
		"REGISTER.TXT"
		"REGISTER.TXT.info"
		"ripgraf.patterns"
                "RIPGRAF.prefs"
	)
	(confirm)
)

(message
        "The RIPgraf installation is now complete! "
	"When you run RIPgraf for the first time, please take a few "
	"moments and update the file preferences from within the "
	"program.\n"
	"Your default FONT directory should be changed to read; " fontdir
	"\n\nand your default ICON directory to read; " icondir
	"\n\nBe sure to select SAVE to make these defaults permanent"
)
(message
	"\n\nRemember, this a SHAREWARE program... If you find it\n"
	"useful, you are expected to register within 30 days\n\n"
	"PLEASE SUPPORT SHAREWARE!"
)
