#pragma libcall CLMailBase CLMAIL_SendA 1e A9803
#pragma libcall CLMailBase CLMAIL_AllocFile 24 0802
#pragma libcall CLMailBase CLMAIL_FreeFile 2a 801
#pragma libcall CLMailBase CLMAIL_FlushAll 30 0
#pragma libcall CLMailBase CLMAIL_Batch 36 0802
#pragma libcall CLMailBase CLMAIL_BoxInfo 3c 9802
#pragma libcall CLMailBase CLMAIL_HandleTrash 42 801
#pragma libcall CLMailBase CLMAIL_TestNetLogin 48 801
#pragma libcall CLMailBase CLMAIL_HandleNetcall 4e A9803
#pragma libcall CLMailBase CLMAIL_DoNetcall 54 B10A9806
#pragma libcall CLMailBase CLMAIL_QuerySpecial 5a 0
/* 14 slots reserviert*/
#pragma libcall CLMailBase CLMAIL_reserved 60 0
#pragma libcall CLMailBase CLMAIL_reserved1 66 0
#pragma libcall CLMailBase CLMAIL_reserved2 6c 0
#pragma libcall CLMailBase CLMAIL_reserved3 72 0
#pragma libcall CLMailBase CLMAIL_reserved4 78 0
#pragma libcall CLMailBase CLMAIL_reserved5 7e 0
#pragma libcall CLMailBase CLMAIL_reserved6 84 0
#pragma libcall CLMailBase CLMAIL_reserved7 8a 0
#pragma libcall CLMailBase CLMAIL_reserved8 90 0
#pragma libcall CLMailBase CLMAIL_reserved9 96 0
#pragma libcall CLMailBase CLMAIL_reserveda 9c 0
#pragma libcall CLMailBase CLMAIL_reservedb a2 0
#pragma libcall CLMailBase CLMAIL_reservedc a8 0
#pragma libcall CLMailBase CLMAIL_reservedd ae 0
#pragma libcall CLMailBase CLMAIL_reservede b4 0
#pragma libcall CLMailBase CLMAIL_reservedf ba 0
#pragma libcall CLMailBase CLMAIL_reservedg c0 0
/* after 25 slots: private calls*/
#pragma libcall CLMailBase CLMAIL_JANUS_GetPrefs c6 0
#pragma libcall CLMailBase CLMAIL_JANUS_SavePrefs cc 0
#pragma libcall CLMailBase CLMAIL_JANUS_AllocPre d2 0802
#pragma libcall CLMailBase CLMAIL_JANUS_FreePre d8 801
