#pragma libcall FileBaseBase fbInitialise 1e 801
#pragma libcall FileBaseBase fbInitBase 24 001
#pragma libcall FileBaseBase fbControl 2a 8002
#pragma libcall FileBaseBase fbQuit 30 0
#pragma libcall FileBaseBase fbGetInfo 36 801
#pragma libcall FileBaseBase fbLoadFileName 3c 19003
#pragma libcall FileBaseBase fbSaveFile 42 0802
#pragma libcall FileBaseBase fbQuickSave 48 0802
#pragma libcall FileBaseBase fbEditFile 4e 9802
#pragma libcall FileBaseBase fbDeleteCatFileName 54 10803
#pragma libcall FileBaseBase fbInitFileScanKey 5a 801
#pragma libcall FileBaseBase fbScanFiles 60 9802
#pragma libcall FileBaseBase fbCloseFileScanKey 66 801
#pragma libcall FileBaseBase fbFindFile 6c 801
#pragma libcall FileBaseBase fbFileExists 72 0802
#pragma libcall FileBaseBase fbSearchFileName 78 801
#pragma libcall FileBaseBase fbRenameCatFile 7e 190804
#pragma libcall FileBaseBase fbFileAreaStats 84 9802
#pragma libcall FileBaseBase fbFileLibraryStats 8a 801
#pragma libcall FileBaseBase fbConfiguration 90 0802
#pragma libcall FileBaseBase fbUpdate 96 001
#pragma libcall FileBaseBase fbRebuild 9c 001
#pragma libcall FileBaseBase fbRecount a2 001
#pragma libcall FileBaseBase fbOptimise a8 001
#pragma libcall FileBaseBase fbTrim ae 001
#pragma libcall FileBaseBase fbConvert b4 001
#pragma libcall FileBaseBase fbDeleteArea ba 001
#pragma libcall FileBaseBase fbRenumberArea c0 1002
#pragma libcall FileBaseBase fbGetFile c6 8002
#pragma libcall FileBaseBase fbFileNumberToName cc 8002
#pragma libcall FileBaseBase fbFileNameToNumber d2 801
#pragma libcall FileBaseBase fbGetIndexFileName d8 9802
#pragma libcall FileBaseBase fbGetFileNoExt de 9802
#pragma libcall FileBaseBase fbLoadFile e4 1002
#pragma libcall FileBaseBase fbDeleteCatFile ea 001
