;
;	Install Script for dRE!WEEk v2.0
; ©1996 Bodo Hoffmann
; 
; $VER: dRE!WEEk.install v2.0 (26-Aug-96)
;

(complete 0)
(run "run /files/welcome")

(if (= @language "deutsch")
	(
		(set	#welcome						(cat	"\nWillkommen zur Installation von\n"
																		"dRE!WEEk v2.0 (fiM) for FAME BBS\n"
																		"Dieses Script installiert dRE!WEEk\n"
																		"auf ihrem AMIGA, so das Sie das DOOR\n"
																		"direkt in Benutzung nehmen könnenn\n\n\n"
																		"Dieses Program ist REGISTERWARE\n"
																		"Um eine volle Version zu bekommen sollten\n"
																		"Sie sich bei mir registrieren lassen, bitte\n"
																		"lesen Sie in dem Amigaguide Document wo und\n"
																		"wie Sie dieses tuen können\n"
															)
		)

		(set	#regdir-prompt			(cat	"Selektieren Sie jetzt bitte das Verzeichnis, in der die registrierten Hauptprogramme liegen"))

		(set	#getinstdir-prompt	(cat	"Bitte wählen sie jetzt das Verzeichnis in dem dRE!WEEk installiert werden soll, eine Schublade wird erzeugt"))
	
		(set	#doorname-prompt		(cat "Bitte wählen Sie jetzt den Name unterdem das Door in der BBS aufzurufen ist"))

		(set	#level-prompt				(cat "Bitte wählen Sie jetzt den Accesslevel unterdem das Door in der BBS abrufbar ist"))

		(set	#convert-help				(cat	"\n\n\n\nDas datenformat hat sich gegenüber der\n"
																		"letzten Version geändert.\n\n"
																		"WEEKTOP_CONVERT wird nun alle datenfiles\n"
																		"in das neue format konvertieren...\n"
															)
		)

		(set	#askfont-prompt			(cat	"Bitte wählen sie nun einen 8 punkt font für das GUI aus, z.B. topaz.font"))
	)
)

(if	(=	@language "english")
	(
		(set #welcome							(cat	"\nWelcome to the Installation of\n"
																		"dRE!WEEk v2.0\n"
																		"This program will install dRE!WEEk\n"
																		"on your AMIGA, so it is ready to use after\n"
																		"this procedure\n\n\n"
																		"This program is REGISTERWARE\n"
																		"To become a full version you should register\n"
																		"my programs, please refer to the AmigaGuide\n"
																		"Document for more informations how and where\n"
																		"you can do this...\n"
															)
		)

		(set	#regdir-prompt			(cat	"Please select now the the drawer, where the registered mainfiles are located"))

		(set	#getinstdir-prompt	(cat	"Please select the drawer where dRE!WEEk should be installed, a drawer will be created"))

		(set	#getinstdir-prompt	(cat	"Please select the drawer where the dRE!WEEk Preferences should be installed, a drawer will be created"))
	
		(set	#doorname-prompt		(cat "Please choose now the name for the door"))

		(set	#level-prompt				(cat "Please choose now the access-level for the door"))

		(set	#convert-help				(cat	"\n\n\n\nThis version of dre!week uses a new\n"
																		"datafile format\n\n"
																		"WEEKTOP_CONVERT will now convert all\n"
																		"existing datafile to this new format"
															)
		)

		(set	#askfont-prompt (cat	"Please select now the font for the GUI, it must have size 8, iE: topaz.font"))
	)
)

(complete 0)
(message	#welcome)

	(set doors		(askdir		(prompt #getinstdir-prompt)
													(help @askdir-help)
													(default	"DOORS:")
								)
	)

	(set prefsdir	(askdir		(prompt #getprefsdir-prompt)
													(help @askdir-help)
													(default	"SYS:PREFS")
								)
	)

	(set	destdir		(tackon doors		"dRE!WEEk"))
	(set	guidedir	(tackon destdir	"Guides"))

	(makedir	destdir		(infos))
	(makedir	guidedir	(infos))
	(makedir	prefsdir	(infos))

	(copyfiles		(source	"/files/dRE!WEEk")
								(dest		destdir)
								(optional nofail askuser)
								(confirm)
	)

	(copyfiles		(source	"/files/dRE!WEEk-CFG")
								(dest		prefsdir)
								(optional nofail askuser)
								(confirm)
	)

	(copyfiles		(source	"/Icons")
								(dest		prefsdir)
								(infos)
								(all)
								(optional nofail askuser)
								(confirm)
	)

	(copyfiles		(source	"/Fonts")
								(dest		"FONTS:")
								(fonts)
								(all)
								(optional nofail askuser)
								(confirm)
	)

	(copyfiles		(source	"/guides")
								(dest		guidedir)
								(infos)
								(all)
								(optional nofail askuser)
								(confirm)
	)

	(copyfiles		(source	"/Pictures")
								(dest		guidedir)
								(infos)
								(all)
								(optional nofail askuser)
								(confirm)
	)

	(copyfiles		(source	"/Headers")
								(dest		destdir)
								(all)
								(optional nofail askuser)
								(confirm)
	)

	(copylib      (prompt "DRE.library")
				        (source "/Libs/DRE.library")
				        (dest   "LIBS:")
        				(confirm)
	)

	(copylib      (prompt "FAME.library")
				        (source "/Libs/FAME.library")
				        (dest   "LIBS:")
        				(confirm)
	)

	(tooltype
		(dest	(tackon	prefsdir	"dRE!WEEk-CFG"))
		(settooltype	"HELPFILE" (tackon guidedir "WEEKTOP.guide"))
		(settooltype	"FONT" "WAREZ.font")
		(settooltype	"FONTSIZE" "8")
	)

	(set	doorname	(askstring	(prompt #doorname-prompt)
															(help		@askstring-help)
															(default	"WEEKTOP")
									)
	)

	(set level	(asknumber	(prompt		#level-prompt)
													(help			@asknumber-help)
													(range		10 255)
													(default	10)
							)
	)

	(set confdir	("FAME:SETTINGS/DOORS/SYSCMD"))
	(set ulstat (tackon destdir "dRE!WEEk"))
	(set make	("/Files/MakeCMD NAME=ULSTAT PATH=%s SERVERNAME=dRE!WEEk STACK=4096 ACSLEVEL=%ld CMDTYPE=-2 MULTINODE PRI=0 DOORTYPE=0 NR NC CF SR SC AR AC RD" ulstat cmd level))
	(run make)

	(set make	("/Files/MakeCMD NAME=%s PATH=%s SERVERNAME=dRE!WEEk STACK=4096 ACSLEVEL=%ld CMDTYPE=-1 MULTINODE PRI=0 DOORTYPE=0 NR NC CF SR SC AR AC RD" doorname cmd level))
	(run make)

	(message	#convert-help)
	(run	"/files/WEEKTOP_CONVERT")
	
	(complete 100)

	(run	"SYS:Utilities/MultiView /Guides/WEEKTOP.guide")
