%BC=7.%TC=4.  System Operator Availability Status  %BC=0.%TC=7.

It would appear that the System Operator can not make it to the terminal
at the moment. By all accounts he should be available so maybe you
ought to try one more page.

If you find that all else fails then maybe you are not making clear
what you wish to chat about.

%TC=1.ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ%TC=3. Continue%TC=1. >>%TC=7.%WAITKEY.