%CLS.%CURSOR=0.%TC=4. ‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹
 €€€%TC=6.%BC=4.You are now in direct Conference with the System Operator.%TC=4.€€€€€€€€€€€€%BC=0.€€€€
 €ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ€ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ€
 €%TC=6. User Name: %TC=7.%-19.19s%TC=6.Level:%TC=7. %-5ld%TC=4.€%TC=3.  << ApT SysOp -> User Chat%TC=4.    €
 €%TC=6.    Handle: %TC=7.%-12.12s                   %TC=4.€%TC=3.  << ApT-Design Support BBS%TC=4.    €
 €%TC=6.     Phone: %TC=7.%-19.19s            %TC=4.€%TC=3.                               %TC=4.€
 €‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹€‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹€

%TC=2.%CURSOR=1.