/* C Headerfile generated by RevUp 1.2 */

#define VERSION		3
#define REVISION	1
#define DATE	"22.7.95"
#define VERS	"UserEditor 3.1"
#define VSTRING	"UserEditor 3.1 (22.7.95)\r\n"
#define VERSTAG	"\0$VER: UserEditor 3.1 (22.7.95)"
