 When entering your biography, please include any interests, hobbies, or
 anything that you feel is important for other users to know about you.
 Enter the biography just as you would any other message, and to view
 other people's biography, type M and then a ? to get a list of the people
 that have written them.  Thanks for taking the time to write one!
 Using the .M <name> you can see the biography of a particular person.