^n *** QWK Configuration Help ***
^n
^n <C>onfigure - This option allows you to setup the rooms you wish to
^n               collect QWK messages from.
^n <R>eset     - This option will reset all the high message pointers
^n               to be the highest message based on the selected options
^n <S>end      - This option toggles the message option to send your message
^n               with the qwk packet or not.
^n <M>aximum   - This option sets the limit of how many messages can be
^n               collected for one packet.  The default is the maximum
^n               configured by the Sysop.
^n <T>ransfer  - Sets the protocol used to download the packet.
^n <P>acket    - Sets the archiver you wish to use to download the packet.
^n <G>oodBye   - Toggles the option to log off after the packet is sent.
^n <H>elp      - This date is displayed.
^n <Q>uit      - Quit and save changes.

