Please send this application to your nearest HUB or the system you intend
to poll for mail.

For details of hubs, please consult a recent BBSNet nodelist, BN-LIST.xxx 

Please only refer your application to Cellular BBS if you are also going to
be collecting mail from us.  Each region is managed by its own RC, so we
can't give you a London node listing if you intend to use another board
to collect from.  However, please feel free to mail the sysop (2:2503/422)
if you have any problems locating a local host.

------------------------------------------------------------------------------
                               APPLICATION FORM
------------------------------------------------------------------------------


HOST BBS you wish to collect from: ________________________________________
if you know there Node_Number:

Your FULL Name.......:
Your Area............:                          (If London please state where)
Your VOICE contact...:                          (only if you want to give it)
----------------------

Your BBS's Name......:
Online Times.........:
BBS's Phone Number...:
Maximum Baudrate.....:
BBS's Software Used..:
Your FIDONET node add:
How "old" is your BBS:

----------------------

Suggested password for
Front End and Areafix:                          (Max 8 characters)

----------------------------------------------------------------------------
