;
; DePack! AmiNet distribution
;
; Installdisk Installationsscript
;
; (c) 1995 Laserdance Productions / T$B
;

echo "Welcome to the DePack!-Installation script !"
echo ""
echo "You'll need a blank disk labelled DePack! or an assign"
echo "named DePack!:"

if EXISTS DePack!:
	echo ""
	echo "Assign/Diskette gefunden."
	ask "Press <RETURN> or <ENTER> to start installation"
	echo ""
	echo "Installation in progress ..."
			; Extract stuff
	lha -D3 x tsb-depack!un.lha depack!:
			; Make changes noticeable from WB
	diskchange >NIL: DePack!:
	echo ""
	echo "Installation complete. Please reset your computer now."
else
	echo "Couldn't find assignment/disk. Try again when"
	echo "you have one!"
	
endif


