;
; DePack! AmiNet distribution
;
; Installdisk Installationsscript
;
; (c) 1995 Laserdance Productions / T$B
;

echo "Willkommen zum DePack!-Installationsscript !"
echo ""
echo "Sie benoetigen eine leere Diskette mit Namen DePack! oder"
echo "ein Assign namens DePack!."

if EXISTS DePack!:
	echo ""
	echo "Assign/Diskette gefunden."
	ask "Druecke <RETURN> oder <ENTER> um Installation zu starten"
	echo ""
	echo "Installation wird gestartet ..."
			; Extract stuff
	lha -D3 x tsb-depack!un.lha depack!:
			; Make changes noticeable from WB
	diskchange >NIL: DePack!:
	echo ""
	echo "Installation beendet !"
	echo "Bitte fuehren Sie einen Reset durch."	
else
	echo "Konnte Assign/Diskette nicht finden."
	echo "Formatieren Sie eine Diskette und probieren Sie es"
	echo "noch einmal."
endif


