/*
** Zeus Shortcut Script
**
** ShutdownZeus.zsc
**
**   - This script shuts down Zeus in 'n' minutes, after informing the
**     user that the BBS is going down, and kicking them off.
**
**     Arguments: [Minutes]
**
** $VER: ShutdownZeus.zsc 1.0 (19.02.96)
** Zeus Bulletin Board System (c)1992-1996 Alex May & Nick Loman
*/

Options Results
Parse Arg Minutes

Address 'ZEUS'

say ''
say 'Zeus Bulletin Board System (c)1992-1996 Alex May & Nick Loman'
say 'Zeus Shutdown Script - written by Nick Loman'
say ''

if Minutes = '' then do
	options prompt 'How many minutes until Zeus shutdown? '
	pull Minutes
	end

if DataType( Minutes, 'N' ) then do
	address command 'Zeus:Bin/SendMsg LINE * MESSAGE "The BBS will be shut down in 'Minutes' minutes!"'
	call delay(minutes*50*60)
	quitzeus
	end
else
	signal usage

exit

Usage:
	say ''
	say 'Usage: ShutdownZeus.scr [Minutes]'
	say ''
	exit
