^n  Citadel-68K QWK Message Processor
^n [D]ownload QWK packet: This will start the process of
   building and downloading a QWK packet
^n [C]onfigure your settings:  This will allow you to setup the rooms
   you wish to have included in a QWK packet
^n [H]elp with QWK Messages:  This information!
^n [G]oodbye, same as a .TQ(Terminate the connection)
^n [Q]uit back to ^nodetitle:  Skip the QWK packet stuff...
^n
