^n *** Room Selection Help ***
^n <*>  Select all Rooms.
^n <L>  List all selected Rooms
^n <+>  Move to next screen of Rooms
^n <T>  To Beginning of list of Rooms
^n <O>  List only the selected Rooms
^n <->  Move to the previous screen of Rooms
^n <R>  Reverse the selection of rooms, all that were not selected are
^n      now selected, and all that were selected are not.
^n <A>  All rooms are listed
^n <Q>  Quit the Room selection
