/* C Headerfile generated by RevUp 1.2 */

#define VERSION		1
#define REVISION	3
#define DATE	"15.10.94"
#define VERS	"XPR 1.3"
#define VSTRING	"XPR 1.3 (15.10.94)\r\n"
#define VERSTAG	"\0$VER: XPR 1.3 (15.10.94)"
